In [221]:
## importing important libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import warnings

warnings.filterwarnings("ignore")

%matplotlib inline

In [222]:
df = pd.read_csv("Travel.csv")
df.head()

,CustomerID,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,Designation,MonthlyIncome
0,200000,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3,3.0,Deluxe,3.0,Single,1.0,1,2,1,0.0,Manager,20993.0
1,200001,0,49.0,Company Invited,1,14.0,Salaried,Male,3,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,2.0,Manager,20130.0
2,200002,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,3,4.0,Basic,3.0,Single,7.0,1,3,0,0.0,Executive,17090.0
3,200003,0,33.0,Company Invited,1,9.0,Salaried,Female,2,3.0,Basic,3.0,Divorced,2.0,1,5,1,1.0,Executive,17909.0
4,200004,0,NaN,Self Enquiry,1,8.0,Small Business,Male,2,3.0,Basic,4.0,Divorced,1.0,0,5,1,0.0,Executive,18468.0

In [223]:
### Check all the categories 
df['Gender'].value_counts()

Gender
Male       2916
Female     1817
Fe Male     155
Name: count, dtype: int64

In [224]:
df['MaritalStatus'].value_counts()

MaritalStatus
Married      2340
Divorced      950
Single        916
Unmarried     682
Name: count, dtype: int64

In [225]:
df['Gender'] = df['Gender'].replace('Fe Male', 'Female')
df['MaritalStatus'] = df['MaritalStatus'].replace('Single', 'Unmarried')

In [226]:
### Check all the categories 
df['Gender'].value_counts()

Gender
Male      2916
Female    1972
Name: count, dtype: int64

In [227]:
## Check Misssing Values
##these are the features with nan value
features_with_na=[features for features in df.columns if df[features].isnull().sum()>=1]
for feature in features_with_na:
    print(feature,np.round(df[feature].isnull().mean()*100,5), '% missing values')

Age 4.62357 % missing values
TypeofContact 0.51146 % missing values
DurationOfPitch 5.13502 % missing values
NumberOfFollowups 0.92062 % missing values
PreferredPropertyStar 0.53191 % missing values
NumberOfTrips 2.86416 % missing values
NumberOfChildrenVisiting 1.35025 % missing values
MonthlyIncome 4.76678 % missing values

In [228]:
# statistics on numerical columns (Null cols)
df[features_with_na].select_dtypes(exclude='object').describe()

,Age,DurationOfPitch,NumberOfFollowups,PreferredPropertyStar,NumberOfTrips,NumberOfChildrenVisiting,MonthlyIncome
count,4662.000000,4637.000000,4843.000000,4862.000000,4748.000000,4822.000000,4655.000000
mean,37.622265,15.490835,3.708445,3.581037,3.236521,1.187267,23619.853491
std,9.316387,8.519643,1.002509,0.798009,1.849019,0.857861,5380.698361
min,18.000000,5.000000,1.000000,3.000000,1.000000,0.000000,1000.000000
25%,31.000000,9.000000,3.000000,3.000000,2.000000,1.000000,20346.000000
50%,36.000000,13.000000,4.000000,3.000000,3.000000,1.000000,22347.000000
75%,44.000000,20.000000,4.000000,4.000000,4.000000,2.000000,25571.000000
max,61.000000,127.000000,6.000000,5.000000,22.000000,3.000000,98678.000000

In [229]:
#Age
df.Age.fillna(df.Age.median(), inplace=True)

#TypeofContract
df.TypeofContact.fillna(df.TypeofContact.mode()[0], inplace=True)

#DurationOfPitch
df.DurationOfPitch.fillna(df.DurationOfPitch.median(), inplace=True)

#NumberOfFollowups
df.NumberOfFollowups.fillna(df.NumberOfFollowups.mode()[0], inplace=True)

#PreferredPropertyStar
df.PreferredPropertyStar.fillna(df.PreferredPropertyStar.mode()[0], inplace=True)

#NumberOfTrips
df.NumberOfTrips.fillna(df.NumberOfTrips.median(), inplace=True)

#NumberOfChildrenVisiting
df.NumberOfChildrenVisiting.fillna(df.NumberOfChildrenVisiting.mode()[0], inplace=True)

#MonthlyIncome
df.MonthlyIncome.fillna(df.MonthlyIncome.median(), inplace=True)

In [230]:
df.head()
df.isnull().sum()

CustomerID                  0
ProdTaken                   0
Age                         0
TypeofContact               0
CityTier                    0
DurationOfPitch             0
Occupation                  0
Gender                      0
NumberOfPersonVisiting      0
NumberOfFollowups           0
ProductPitched              0
PreferredPropertyStar       0
MaritalStatus               0
NumberOfTrips               0
Passport                    0
PitchSatisfactionScore      0
OwnCar                      0
NumberOfChildrenVisiting    0
Designation                 0
MonthlyIncome               0
dtype: int64

In [231]:
df.head()

,CustomerID,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,Designation,MonthlyIncome
0,200000,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3,3.0,Deluxe,3.0,Unmarried,1.0,1,2,1,0.0,Manager,20993.0
1,200001,0,49.0,Company Invited,1,14.0,Salaried,Male,3,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,2.0,Manager,20130.0
2,200002,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,3,4.0,Basic,3.0,Unmarried,7.0,1,3,0,0.0,Executive,17090.0
3,200003,0,33.0,Company Invited,1,9.0,Salaried,Female,2,3.0,Basic,3.0,Divorced,2.0,1,5,1,1.0,Executive,17909.0
4,200004,0,36.0,Self Enquiry,1,8.0,Small Business,Male,2,3.0,Basic,4.0,Divorced,1.0,0,5,1,0.0,Executive,18468.0

In [232]:
# create new column for feature
df['TotalVisiting'] = df['NumberOfPersonVisiting'] + df['NumberOfChildrenVisiting']
df.drop(columns=['NumberOfPersonVisiting', 'NumberOfChildrenVisiting'], axis=1, inplace=True)

In [233]:
## get all the numeric features
num_features = [feature for feature in df.columns if df[feature].dtype != 'O']
print('Num of Numerical Features :', len(num_features))

Num of Numerical Features : 13

In [234]:
##categorical features
cat_features = [feature for feature in df.columns if df[feature].dtype == 'O']
print('Num of Categorical Features :', len(cat_features))

Num of Categorical Features : 6

In [235]:
## Discrete features
discrete_features=[feature for feature in num_features if len(df[feature].unique())<=25]
print('Num of Discrete Features :',len(discrete_features))

Num of Discrete Features : 9

In [236]:
from sklearn.model_selection import train_test_split
X = df.drop(['ProdTaken'], axis=1)
y = df['ProdTaken']

In [237]:
# separate dataset into train and test
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)
X_train.shape, X_test.shape

((3910, 18), (978, 18))

In [238]:
# Create Column Transformer with 3 types of transformers
cat_features = X.select_dtypes(include="object").columns
num_features = X.select_dtypes(exclude="object").columns

from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer

numeric_transformer = StandardScaler()
oh_transformer = OneHotEncoder(drop='first')

preprocessor = ColumnTransformer(
    [
         ("OneHotEncoder", oh_transformer, cat_features),
          ("StandardScaler", numeric_transformer, num_features)
    ]
)

In [239]:
## applying Trnsformation in training(fit_transform)
X_train=preprocessor.fit_transform(X_train)

In [240]:
pd.DataFrame(X_train)

,0,1,2,3,4,5,6,7,8,9,...,17,18,19,20,21,22,23,24,25,26
0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,...,-0.721400,-1.020350,1.284279,-0.725271,-0.127737,-0.632399,0.679690,0.782966,-0.382245,-0.774151
1,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,...,-0.721400,0.690023,0.282777,-0.725271,1.511598,-0.632399,0.679690,0.782966,-0.459799,0.643615
2,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.721400,-1.020350,0.282777,1.771041,0.418708,-0.632399,0.679690,0.782966,-0.245196,-0.065268
3,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,...,-0.721400,-1.020350,1.284279,-0.725271,-0.127737,-0.632399,1.408395,-1.277194,0.213475,-0.065268
4,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.721400,2.400396,-1.720227,-0.725271,1.511598,-0.632399,-0.049015,-1.277194,-0.024889,2.061382
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3905,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,...,-0.721400,-0.653841,1.284279,-0.725271,-0.674182,-0.632399,-1.506426,0.782966,-0.536973,0.643615
3906,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,1.455047,-0.898180,-0.718725,1.771041,-1.220627,-0.632399,1.408395,0.782966,1.529609,-0.065268
3907,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.455047,1.545210,0.282777,-0.725271,2.058043,-0.632399,-0.777720,0.782966,-0.360576,0.643615
3908,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,...,1.455047,1.789549,1.284279,-0.725271,-0.127737,-0.632399,-1.506426,0.782966,-0.252799,0.643615
3909,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,-0.721400,-0.776011,0.282777,-0.725271,-1.220627,1.581280,-0.049015,-1.277194,-1.082511,-1.483035

In [241]:
## apply tansformation on test(transform)
X_test=preprocessor.transform(X_test)

In [242]:
X_test

array([[ 0.        ,  0.        ,  0.        , ..., -1.2771941 ,
        -0.73751038, -0.77415132],
       [ 1.        ,  0.        ,  0.        , ..., -1.2771941 ,
        -0.6704111 , -0.06526803],
       [ 1.        ,  0.        ,  0.        , ...,  0.78296635,
        -0.4208322 , -0.77415132],
       ...,
       [ 0.        ,  1.        ,  0.        , ...,  0.78296635,
         0.69001249,  0.64361526],
       [ 1.        ,  0.        ,  0.        , ...,  0.78296635,
        -0.22827818, -0.77415132],
       [ 1.        ,  1.        ,  0.        , ...,  0.78296635,
        -0.44611323,  2.06138184]], shape=(978, 27))

In [243]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,recall_score,classification_report,confusion_matrix,precision_score,recall_score,f1_score,roc_auc_score,roc_curve

In [244]:
models={
    "Random Forest":RandomForestClassifier(),
    "Decision Tree":DecisionTreeClassifier(),
    "LogisticRegression":LogisticRegression()
}
for i in range(len(list(models))):
    model=list(models.values())[i]
    model.fit(X_train,y_train)
    #prediction
    y_train_pred=model.predict(X_train)
    y_test_pred=model.predict(X_test)
    #training set perforamance
    model_train_accuracy=accuracy_score(y_train,y_train_pred)
    model_train_f1=f1_score(y_train,y_train_pred,average="weighted")
    model_train_precision=precision_score(y_train,y_train_pred)
    model_train_rocau_score=roc_auc_score(y_train,y_train_pred)
    model_train_recall = recall_score(y_train, y_train_pred) 

    model_test_accuracy=accuracy_score(y_test,y_test_pred)
    model_test_f1=f1_score(y_test,y_test_pred,average="weighted")
    model_test_precision=precision_score(y_test,y_test_pred)
    model_test_rocua_score=roc_auc_score(y_test,y_test_pred)
    model_test_recall = recall_score(y_test, y_test_pred) # Calculate Recall

    print(list(models.keys())[i])
    print("\nModel performance for Training set")
    print("- Accuracy:  {:.4f}".format(model_train_accuracy))
    print("- F1 Score:  {:.4f}".format(model_train_f1))
    print("- Precision: {:.4f}".format(model_train_precision))
    print("- ROC AUC:   {:.4f}".format(model_train_rocau_score))
    print('- Recall: {:.4f}'.format(model_train_recall))

    print("\nModel performance for Test set")
    print("- Accuracy:  {:.4f}".format(model_test_accuracy))
    print("- F1 Score:  {:.4f}".format(model_test_f1))
    print("- Precision: {:.4f}".format(model_test_precision))
    print('- Recall: {:.4f}'.format(model_test_recall))
    print("- ROC AUC:   {:.4f}".format(model_test_rocua_score))
    print("="*50)

Random Forest

Model performance for Training set
- Accuracy:  1.0000
- F1 Score:  1.0000
- Precision: 1.0000
- ROC AUC:   1.0000
- Recall: 1.0000

Model performance for Test set
- Accuracy:  0.9100
- F1 Score:  0.9012
- Precision: 0.9402
- Recall: 0.5759
- ROC AUC:   0.7835
==================================================
Decision Tree

Model performance for Training set
- Accuracy:  1.0000
- F1 Score:  1.0000
- Precision: 1.0000
- ROC AUC:   1.0000
- Recall: 1.0000

Model performance for Test set
- Accuracy:  0.8937
- F1 Score:  0.8919
- Precision: 0.7486
- Recall: 0.6859
- ROC AUC:   0.8150
==================================================
LogisticRegression

Model performance for Training set
- Accuracy:  0.8468
- F1 Score:  0.8214
- Precision: 0.7044
- ROC AUC:   0.6389
- Recall: 0.3073

Model performance for Test set
- Accuracy:  0.8354
- F1 Score:  0.8086
- Precision: 0.6786
- Recall: 0.2984
- ROC AUC:   0.6321
==================================================

In [245]:
## Hyperparameter Training
rf_params = {"max_depth": [5, 8, 15, None, 10],
             "max_features": [5, 7, "auto", 8],
             "min_samples_split": [2, 8, 15, 20],
             "n_estimators": [100, 200, 500, 1000]}

In [246]:
rf_params

{'max_depth': [5, 8, 15, None, 10],
 'max_features': [5, 7, 'auto', 8],
 'min_samples_split': [2, 8, 15, 20],
 'n_estimators': [100, 200, 500, 1000]}

In [248]:
randomcv_models=[
    ("RF",RandomForestClassifier(),rf_params)
]

In [249]:
from sklearn.model_selection import RandomizedSearchCV
model_params={}
for name,model,params in randomcv_models:
    random=RandomizedSearchCV(estimator=model,
                              param_distributions=params,n_iter=100,cv=3,verbose=2,n_jobs=1)
    random.fit(X_train,y_train)
    model_params[name]=random.best_params_
for model_name in model_params:
    print(f"------best params for {model_name}------")
    print(model_params[model_name])

Fitting 3 folds for each of 100 candidates, totalling 300 fits
[CV] END max_depth=15, max_features=8, min_samples_split=20, n_estimators=200; total time=   0.9s
[CV] END max_depth=15, max_features=8, min_samples_split=20, n_estimators=200; total time=   1.0s
[CV] END max_depth=15, max_features=8, min_samples_split=20, n_estimators=200; total time=   1.0s
[CV] END max_depth=15, max_features=auto, min_samples_split=15, n_estimators=1000; total time=   0.0s
[CV] END max_depth=15, max_features=auto, min_samples_split=15, n_estimators=1000; total time=   0.0s
[CV] END max_depth=15, max_features=auto, min_samples_split=15, n_estimators=1000; total time=   0.0s
[CV] END max_depth=8, max_features=8, min_samples_split=8, n_estimators=200; total time=   0.8s
[CV] END max_depth=8, max_features=8, min_samples_split=8, n_estimators=200; total time=   0.8s
[CV] END max_depth=8, max_features=8, min_samples_split=8, n_estimators=200; total time=   0.8s
[CV] END max_depth=8, max_features=5, min_samples_split=15, n_estimators=500; total time=   2.2s
[CV] END max_depth=8, max_features=5, min_samples_split=15, n_estimators=500; total time=   1.8s
[CV] END max_depth=8, max_features=5, min_samples_split=15, n_estimators=500; total time=   1.7s
[CV] END max_depth=8, max_features=7, min_samples_split=8, n_estimators=500; total time=   2.2s
[CV] END max_depth=8, max_features=7, min_samples_split=8, n_estimators=500; total time=   2.1s
[CV] END max_depth=8, max_features=7, min_samples_split=8, n_estimators=500; total time=   2.4s
[CV] END max_depth=8, max_features=8, min_samples_split=15, n_estimators=1000; total time=   4.5s
[CV] END max_depth=8, max_features=8, min_samples_split=15, n_estimators=1000; total time=   4.6s
[CV] END max_depth=8, max_features=8, min_samples_split=15, n_estimators=1000; total time=   4.9s
[CV] END max_depth=None, max_features=7, min_samples_split=15, n_estimators=500; total time=   2.8s
[CV] END max_depth=None, max_features=7, min_samples_split=15, n_estimators=500; total time=   2.7s
[CV] END max_depth=None, max_features=7, min_samples_split=15, n_estimators=500; total time=   2.7s
[CV] END max_depth=5, max_features=8, min_samples_split=8, n_estimators=1000; total time=   3.6s
[CV] END max_depth=5, max_features=8, min_samples_split=8, n_estimators=1000; total time=   3.7s
[CV] END max_depth=5, max_features=8, min_samples_split=8, n_estimators=1000; total time=   3.5s
[CV] END max_depth=8, max_features=7, min_samples_split=2, n_estimators=500; total time=   2.1s
[CV] END max_depth=8, max_features=7, min_samples_split=2, n_estimators=500; total time=   2.1s
[CV] END max_depth=8, max_features=7, min_samples_split=2, n_estimators=500; total time=   1.9s
[CV] END max_depth=15, max_features=8, min_samples_split=15, n_estimators=100; total time=   0.4s
[CV] END max_depth=15, max_features=8, min_samples_split=15, n_estimators=100; total time=   0.4s
[CV] END max_depth=15, max_features=8, min_samples_split=15, n_estimators=100; total time=   0.4s
[CV] END max_depth=5, max_features=7, min_samples_split=8, n_estimators=500; total time=   1.6s
[CV] END max_depth=5, max_features=7, min_samples_split=8, n_estimators=500; total time=   1.5s
[CV] END max_depth=5, max_features=7, min_samples_split=8, n_estimators=500; total time=   1.6s
[CV] END max_depth=8, max_features=8, min_samples_split=20, n_estimators=1000; total time=   4.1s
[CV] END max_depth=8, max_features=8, min_samples_split=20, n_estimators=1000; total time=   4.0s
[CV] END max_depth=8, max_features=8, min_samples_split=20, n_estimators=1000; total time=   4.0s
[CV] END max_depth=5, max_features=8, min_samples_split=8, n_estimators=500; total time=   1.5s
[CV] END max_depth=5, max_features=8, min_samples_split=8, n_estimators=500; total time=   1.5s
[CV] END max_depth=5, max_features=8, min_samples_split=8, n_estimators=500; total time=   1.5s
[CV] END max_depth=10, max_features=5, min_samples_split=8, n_estimators=200; total time=   0.6s
[CV] END max_depth=10, max_features=5, min_samples_split=8, n_estimators=200; total time=   0.6s
[CV] END max_depth=10, max_features=5, min_samples_split=8, n_estimators=200; total time=   0.6s
[CV] END max_depth=None, max_features=auto, min_samples_split=2, n_estimators=1000; total time=   0.0s
[CV] END max_depth=None, max_features=auto, min_samples_split=2, n_estimators=1000; total time=   0.0s
[CV] END max_depth=None, max_features=auto, min_samples_split=2, n_estimators=1000; total time=   0.0s
[CV] END max_depth=10, max_features=7, min_samples_split=8, n_estimators=500; total time=   2.0s
[CV] END max_depth=10, max_features=7, min_samples_split=8, n_estimators=500; total time=   2.1s
[CV] END max_depth=10, max_features=7, min_samples_split=8, n_estimators=500; total time=   2.2s
[CV] END max_depth=15, max_features=5, min_samples_split=2, n_estimators=1000; total time=   4.0s
[CV] END max_depth=15, max_features=5, min_samples_split=2, n_estimators=1000; total time=   4.1s
[CV] END max_depth=15, max_features=5, min_samples_split=2, n_estimators=1000; total time=   4.2s
[CV] END max_depth=15, max_features=5, min_samples_split=15, n_estimators=1000; total time=   3.7s
[CV] END max_depth=15, max_features=5, min_samples_split=15, n_estimators=1000; total time=   5.0s
[CV] END max_depth=15, max_features=5, min_samples_split=15, n_estimators=1000; total time=   4.2s
[CV] END max_depth=10, max_features=8, min_samples_split=2, n_estimators=200; total time=   0.9s
[CV] END max_depth=10, max_features=8, min_samples_split=2, n_estimators=200; total time=   1.1s
[CV] END max_depth=10, max_features=8, min_samples_split=2, n_estimators=200; total time=   0.9s
[CV] END max_depth=None, max_features=auto, min_samples_split=2, n_estimators=500; total time=   0.0s
[CV] END max_depth=None, max_features=auto, min_samples_split=2, n_estimators=500; total time=   0.0s
[CV] END max_depth=None, max_features=auto, min_samples_split=2, n_estimators=500; total time=   0.0s
[CV] END max_depth=10, max_features=auto, min_samples_split=20, n_estimators=200; total time=   0.0s
[CV] END max_depth=10, max_features=auto, min_samples_split=20, n_estimators=200; total time=   0.0s
[CV] END max_depth=10, max_features=auto, min_samples_split=20, n_estimators=200; total time=   0.0s
[CV] END max_depth=15, max_features=5, min_samples_split=2, n_estimators=100; total time=   0.3s
[CV] END max_depth=15, max_features=5, min_samples_split=2, n_estimators=100; total time=   0.3s
[CV] END max_depth=15, max_features=5, min_samples_split=2, n_estimators=100; total time=   0.4s
[CV] END max_depth=10, max_features=5, min_samples_split=20, n_estimators=500; total time=   1.7s
[CV] END max_depth=10, max_features=5, min_samples_split=20, n_estimators=500; total time=   1.7s
[CV] END max_depth=10, max_features=5, min_samples_split=20, n_estimators=500; total time=   1.7s
[CV] END max_depth=8, max_features=5, min_samples_split=8, n_estimators=1000; total time=   3.2s
[CV] END max_depth=8, max_features=5, min_samples_split=8, n_estimators=1000; total time=   3.4s
[CV] END max_depth=8, max_features=5, min_samples_split=8, n_estimators=1000; total time=   3.5s
[CV] END max_depth=5, max_features=auto, min_samples_split=20, n_estimators=200; total time=   0.0s
[CV] END max_depth=5, max_features=auto, min_samples_split=20, n_estimators=200; total time=   0.0s
[CV] END max_depth=5, max_features=auto, min_samples_split=20, n_estimators=200; total time=   0.0s
[CV] END max_depth=10, max_features=5, min_samples_split=15, n_estimators=1000; total time=   4.4s
[CV] END max_depth=10, max_features=5, min_samples_split=15, n_estimators=1000; total time=   3.8s
[CV] END max_depth=10, max_features=5, min_samples_split=15, n_estimators=1000; total time=   4.1s
[CV] END max_depth=15, max_features=8, min_samples_split=15, n_estimators=1000; total time=   6.0s
[CV] END max_depth=15, max_features=8, min_samples_split=15, n_estimators=1000; total time=   5.5s
[CV] END max_depth=15, max_features=8, min_samples_split=15, n_estimators=1000; total time=   5.9s
[CV] END max_depth=8, max_features=7, min_samples_split=8, n_estimators=200; total time=   0.8s
[CV] END max_depth=8, max_features=7, min_samples_split=8, n_estimators=200; total time=   0.8s
[CV] END max_depth=8, max_features=7, min_samples_split=8, n_estimators=200; total time=   1.0s
[CV] END max_depth=5, max_features=5, min_samples_split=15, n_estimators=500; total time=   1.7s
[CV] END max_depth=5, max_features=5, min_samples_split=15, n_estimators=500; total time=   1.5s
[CV] END max_depth=5, max_features=5, min_samples_split=15, n_estimators=500; total time=   1.6s
[CV] END max_depth=10, max_features=8, min_samples_split=15, n_estimators=200; total time=   1.0s
[CV] END max_depth=10, max_features=8, min_samples_split=15, n_estimators=200; total time=   1.0s
[CV] END max_depth=10, max_features=8, min_samples_split=15, n_estimators=200; total time=   1.1s
[CV] END max_depth=8, max_features=5, min_samples_split=8, n_estimators=100; total time=   0.3s
[CV] END max_depth=8, max_features=5, min_samples_split=8, n_estimators=100; total time=   0.3s
[CV] END max_depth=8, max_features=5, min_samples_split=8, n_estimators=100; total time=   0.4s
[CV] END max_depth=8, max_features=8, min_samples_split=15, n_estimators=200; total time=   1.0s
[CV] END max_depth=8, max_features=8, min_samples_split=15, n_estimators=200; total time=   1.1s
[CV] END max_depth=8, max_features=8, min_samples_split=15, n_estimators=200; total time=   0.9s
[CV] END max_depth=8, max_features=8, min_samples_split=20, n_estimators=100; total time=   0.4s
[CV] END max_depth=8, max_features=8, min_samples_split=20, n_estimators=100; total time=   0.6s
[CV] END max_depth=8, max_features=8, min_samples_split=20, n_estimators=100; total time=   0.4s
[CV] END max_depth=8, max_features=7, min_samples_split=20, n_estimators=500; total time=   2.3s
[CV] END max_depth=8, max_features=7, min_samples_split=20, n_estimators=500; total time=   2.6s
[CV] END max_depth=8, max_features=7, min_samples_split=20, n_estimators=500; total time=   2.3s
[CV] END max_depth=5, max_features=auto, min_samples_split=8, n_estimators=100; total time=   0.0s
[CV] END max_depth=5, max_features=auto, min_samples_split=8, n_estimators=100; total time=   0.0s
[CV] END max_depth=5, max_features=auto, min_samples_split=8, n_estimators=100; total time=   0.0s
[CV] END max_depth=5, max_features=8, min_samples_split=2, n_estimators=500; total time=   2.3s
[CV] END max_depth=5, max_features=8, min_samples_split=2, n_estimators=500; total time=   2.0s
[CV] END max_depth=5, max_features=8, min_samples_split=2, n_estimators=500; total time=   1.7s
[CV] END max_depth=5, max_features=7, min_samples_split=15, n_estimators=1000; total time=   3.2s
[CV] END max_depth=5, max_features=7, min_samples_split=15, n_estimators=1000; total time=   3.1s
[CV] END max_depth=5, max_features=7, min_samples_split=15, n_estimators=1000; total time=   3.2s
[CV] END max_depth=8, max_features=7, min_samples_split=2, n_estimators=200; total time=   0.8s
[CV] END max_depth=8, max_features=7, min_samples_split=2, n_estimators=200; total time=   0.8s
[CV] END max_depth=8, max_features=7, min_samples_split=2, n_estimators=200; total time=   0.8s
[CV] END max_depth=8, max_features=auto, min_samples_split=20, n_estimators=100; total time=   0.0s
[CV] END max_depth=8, max_features=auto, min_samples_split=20, n_estimators=100; total time=   0.0s
[CV] END max_depth=8, max_features=auto, min_samples_split=20, n_estimators=100; total time=   0.0s
[CV] END max_depth=None, max_features=8, min_samples_split=8, n_estimators=100; total time=   0.4s
[CV] END max_depth=None, max_features=8, min_samples_split=8, n_estimators=100; total time=   0.5s
[CV] END max_depth=None, max_features=8, min_samples_split=8, n_estimators=100; total time=   0.6s
[CV] END max_depth=5, max_features=5, min_samples_split=20, n_estimators=100; total time=   0.2s
[CV] END max_depth=5, max_features=5, min_samples_split=20, n_estimators=100; total time=   0.2s
[CV] END max_depth=5, max_features=5, min_samples_split=20, n_estimators=100; total time=   0.2s
[CV] END max_depth=10, max_features=7, min_samples_split=8, n_estimators=100; total time=   0.4s
[CV] END max_depth=10, max_features=7, min_samples_split=8, n_estimators=100; total time=   0.4s
[CV] END max_depth=10, max_features=7, min_samples_split=8, n_estimators=100; total time=   0.4s
[CV] END max_depth=8, max_features=8, min_samples_split=8, n_estimators=1000; total time=   5.1s
[CV] END max_depth=8, max_features=8, min_samples_split=8, n_estimators=1000; total time=   5.2s
[CV] END max_depth=8, max_features=8, min_samples_split=8, n_estimators=1000; total time=   4.8s
[CV] END max_depth=10, max_features=8, min_samples_split=2, n_estimators=500; total time=   2.8s
[CV] END max_depth=10, max_features=8, min_samples_split=2, n_estimators=500; total time=   2.9s
[CV] END max_depth=10, max_features=8, min_samples_split=2, n_estimators=500; total time=   3.1s
[CV] END max_depth=10, max_features=7, min_samples_split=20, n_estimators=1000; total time=   4.8s
[CV] END max_depth=10, max_features=7, min_samples_split=20, n_estimators=1000; total time=   5.2s
[CV] END max_depth=10, max_features=7, min_samples_split=20, n_estimators=1000; total time=   5.1s
[CV] END max_depth=10, max_features=7, min_samples_split=15, n_estimators=200; total time=   1.0s
[CV] END max_depth=10, max_features=7, min_samples_split=15, n_estimators=200; total time=   0.9s
[CV] END max_depth=10, max_features=7, min_samples_split=15, n_estimators=200; total time=   0.9s
[CV] END max_depth=5, max_features=7, min_samples_split=8, n_estimators=100; total time=   0.2s
[CV] END max_depth=5, max_features=7, min_samples_split=8, n_estimators=100; total time=   0.2s
[CV] END max_depth=5, max_features=7, min_samples_split=8, n_estimators=100; total time=   0.2s
[CV] END max_depth=10, max_features=7, min_samples_split=8, n_estimators=1000; total time=   5.9s
[CV] END max_depth=10, max_features=7, min_samples_split=8, n_estimators=1000; total time=   6.6s
[CV] END max_depth=10, max_features=7, min_samples_split=8, n_estimators=1000; total time=   7.9s
[CV] END max_depth=15, max_features=5, min_samples_split=2, n_estimators=200; total time=   1.6s
[CV] END max_depth=15, max_features=5, min_samples_split=2, n_estimators=200; total time=   2.0s
[CV] END max_depth=15, max_features=5, min_samples_split=2, n_estimators=200; total time=   2.2s
[CV] END max_depth=10, max_features=auto, min_samples_split=8, n_estimators=100; total time=   0.0s
[CV] END max_depth=10, max_features=auto, min_samples_split=8, n_estimators=100; total time=   0.0s
[CV] END max_depth=10, max_features=auto, min_samples_split=8, n_estimators=100; total time=   0.0s
[CV] END max_depth=8, max_features=8, min_samples_split=15, n_estimators=100; total time=   0.7s
[CV] END max_depth=8, max_features=8, min_samples_split=15, n_estimators=100; total time=   0.7s
[CV] END max_depth=8, max_features=8, min_samples_split=15, n_estimators=100; total time=   0.8s
[CV] END max_depth=5, max_features=8, min_samples_split=2, n_estimators=200; total time=   1.2s
[CV] END max_depth=5, max_features=8, min_samples_split=2, n_estimators=200; total time=   1.2s
[CV] END max_depth=5, max_features=8, min_samples_split=2, n_estimators=200; total time=   1.5s
[CV] END max_depth=15, max_features=auto, min_samples_split=2, n_estimators=1000; total time=   0.0s
[CV] END max_depth=15, max_features=auto, min_samples_split=2, n_estimators=1000; total time=   0.0s
[CV] END max_depth=15, max_features=auto, min_samples_split=2, n_estimators=1000; total time=   0.0s
[CV] END max_depth=15, max_features=5, min_samples_split=8, n_estimators=1000; total time=  10.4s
[CV] END max_depth=15, max_features=5, min_samples_split=8, n_estimators=1000; total time=   9.1s
[CV] END max_depth=15, max_features=5, min_samples_split=8, n_estimators=1000; total time=   6.5s
[CV] END max_depth=15, max_features=auto, min_samples_split=15, n_estimators=100; total time=   0.0s
[CV] END max_depth=15, max_features=auto, min_samples_split=15, n_estimators=100; total time=   0.0s
[CV] END max_depth=15, max_features=auto, min_samples_split=15, n_estimators=100; total time=   0.0s
[CV] END max_depth=None, max_features=auto, min_samples_split=8, n_estimators=500; total time=   0.0s
[CV] END max_depth=None, max_features=auto, min_samples_split=8, n_estimators=500; total time=   0.0s
[CV] END max_depth=None, max_features=auto, min_samples_split=8, n_estimators=500; total time=   0.0s
[CV] END max_depth=None, max_features=8, min_samples_split=2, n_estimators=200; total time=   2.4s
[CV] END max_depth=None, max_features=8, min_samples_split=2, n_estimators=200; total time=   2.7s
[CV] END max_depth=None, max_features=8, min_samples_split=2, n_estimators=200; total time=   2.3s
[CV] END max_depth=None, max_features=auto, min_samples_split=15, n_estimators=1000; total time=   0.0s
[CV] END max_depth=None, max_features=auto, min_samples_split=15, n_estimators=1000; total time=   0.0s
[CV] END max_depth=None, max_features=auto, min_samples_split=15, n_estimators=1000; total time=   0.0s
[CV] END max_depth=5, max_features=7, min_samples_split=2, n_estimators=500; total time=   2.4s
[CV] END max_depth=5, max_features=7, min_samples_split=2, n_estimators=500; total time=   3.2s
[CV] END max_depth=5, max_features=7, min_samples_split=2, n_estimators=500; total time=   3.5s
[CV] END max_depth=8, max_features=7, min_samples_split=15, n_estimators=1000; total time=   7.3s
[CV] END max_depth=8, max_features=7, min_samples_split=15, n_estimators=1000; total time=   6.6s
[CV] END max_depth=8, max_features=7, min_samples_split=15, n_estimators=1000; total time=   6.2s
[CV] END max_depth=None, max_features=8, min_samples_split=15, n_estimators=200; total time=   1.5s
[CV] END max_depth=None, max_features=8, min_samples_split=15, n_estimators=200; total time=   1.5s
[CV] END max_depth=None, max_features=8, min_samples_split=15, n_estimators=200; total time=   1.6s
[CV] END max_depth=8, max_features=5, min_samples_split=2, n_estimators=500; total time=   3.0s
[CV] END max_depth=8, max_features=5, min_samples_split=2, n_estimators=500; total time=   2.9s
[CV] END max_depth=8, max_features=5, min_samples_split=2, n_estimators=500; total time=   3.2s
[CV] END max_depth=5, max_features=auto, min_samples_split=20, n_estimators=500; total time=   0.0s
[CV] END max_depth=5, max_features=auto, min_samples_split=20, n_estimators=500; total time=   0.0s
[CV] END max_depth=5, max_features=auto, min_samples_split=20, n_estimators=500; total time=   0.0s
[CV] END max_depth=5, max_features=7, min_samples_split=20, n_estimators=200; total time=   0.9s
[CV] END max_depth=5, max_features=7, min_samples_split=20, n_estimators=200; total time=   1.0s
[CV] END max_depth=5, max_features=7, min_samples_split=20, n_estimators=200; total time=   1.1s
[CV] END max_depth=8, max_features=8, min_samples_split=8, n_estimators=500; total time=   2.7s

KeyboardInterrupt:

In [ ]:
models={
    
   
}

In [250]:
models={
     "Random Forest":RandomForestClassifier(n_estimators=1000,min_samples_split=2,
                                          max_features=7,max_depth=None),
    "Decision Tree":DecisionTreeClassifier(),
    "LogisticRegression":LogisticRegression()
}
for i in range(len(list(models))):
    model=list(models.values())[i]
    model.fit(X_train,y_train)
    #prediction
    y_train_pred=model.predict(X_train)
    y_test_pred=model.predict(X_test)
    #training set perforamance
    model_train_accuracy=accuracy_score(y_train,y_train_pred)
    model_train_f1=f1_score(y_train,y_train_pred,average="weighted")
    model_train_precision=precision_score(y_train,y_train_pred)
    model_train_rocau_score=roc_auc_score(y_train,y_train_pred)
    model_train_recall = recall_score(y_train, y_train_pred) 

    model_test_accuracy=accuracy_score(y_test,y_test_pred)
    model_test_f1=f1_score(y_test,y_test_pred,average="weighted")
    model_test_precision=precision_score(y_test,y_test_pred)
    model_test_rocua_score=roc_auc_score(y_test,y_test_pred)
    model_test_recall = recall_score(y_test, y_test_pred) # Calculate Recall

    print(list(models.keys())[i])
    print("\nModel performance for Training set")
    print("- Accuracy:  {:.4f}".format(model_train_accuracy))
    print("- F1 Score:  {:.4f}".format(model_train_f1))
    print("- Precision: {:.4f}".format(model_train_precision))
    print("- ROC AUC:   {:.4f}".format(model_train_rocau_score))
    print('- Recall: {:.4f}'.format(model_train_recall))

    print("\nModel performance for Test set")
    print("- Accuracy:  {:.4f}".format(model_test_accuracy))
    print("- F1 Score:  {:.4f}".format(model_test_f1))
    print("- Precision: {:.4f}".format(model_test_precision))
    print('- Recall: {:.4f}'.format(model_test_recall))
    print("- ROC AUC:   {:.4f}".format(model_test_rocua_score))
    print("="*50)

Random Forest

Model performance for Training set
- Accuracy:  1.0000
- F1 Score:  1.0000
- Precision: 1.0000
- ROC AUC:   1.0000
- Recall: 1.0000

Model performance for Test set
- Accuracy:  0.9182
- F1 Score:  0.9105
- Precision: 0.9664
- Recall: 0.6021
- ROC AUC:   0.7985
==================================================
Decision Tree

Model performance for Training set
- Accuracy:  1.0000
- F1 Score:  1.0000
- Precision: 1.0000
- ROC AUC:   1.0000
- Recall: 1.0000

Model performance for Test set
- Accuracy:  0.9029
- F1 Score:  0.9009
- Precision: 0.7791
- Recall: 0.7016
- ROC AUC:   0.8266
==================================================
LogisticRegression

Model performance for Training set
- Accuracy:  0.8468
- F1 Score:  0.8214
- Precision: 0.7044
- ROC AUC:   0.6389
- Recall: 0.3073

Model performance for Test set
- Accuracy:  0.8354
- F1 Score:  0.8086
- Precision: 0.6786
- Recall: 0.2984
- ROC AUC:   0.6321
==================================================