In [204]:
import seaborn as sns
data=sns.load_dataset("tips")

In [205]:
data.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [206]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB

In [207]:
data["sex"].value_counts()

sex
Male      157
Female     87
Name: count, dtype: int64

In [208]:
data["smoker"].value_counts()

smoker
No     151
Yes     93
Name: count, dtype: int64

In [209]:
data["day"].value_counts()

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64

In [210]:
data["time"].value_counts()

time
Dinner    176
Lunch      68
Name: count, dtype: int64

In [211]:
#feature encoding[label][onehot]

In [212]:
#indipendend and dependede features
data.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [213]:
X=data[[ 'tip', 'sex', 'smoker', 'day', 'time', 'size']]

In [214]:
y=data["total_bill"]

In [215]:
from sklearn.model_selection import train_test_split

In [216]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=42)

In [217]:
X_train

      tip     sex smoker  day    time  size
115  3.50  Female     No  Sun  Dinner     2
181  5.65    Male    Yes  Sun  Dinner     2
225  2.50  Female    Yes  Fri   Lunch     2
68   2.01    Male     No  Sat  Dinner     2
104  4.08  Female     No  Sat  Dinner     2
..    ...     ...    ...  ...     ...   ...
106  4.06    Male    Yes  Sat  Dinner     2
14   3.02  Female     No  Sun  Dinner     2
92   1.00  Female    Yes  Fri  Dinner     2
179  3.55    Male    Yes  Sun  Dinner     2
102  2.50  Female    Yes  Sat  Dinner     3

[183 rows x 6 columns]

In [218]:
from sklearn.preprocessing import LabelEncoder

In [219]:
le1=LabelEncoder()
le2=LabelEncoder()
le3=LabelEncoder()

In [220]:
X_train["sex"]=le1.fit_transform(X_train['sex'])
X_train["smoker"]=le2.fit_transform(X_train["smoker"])
X_train["time"]=le3.fit_transform(X_train["time"])

In [221]:
X_train

      tip  sex  smoker  day  time  size
115  3.50    0       0  Sun     0     2
181  5.65    1       1  Sun     0     2
225  2.50    0       1  Fri     1     2
68   2.01    1       0  Sat     0     2
104  4.08    0       0  Sat     0     2
..    ...  ...     ...  ...   ...   ...
106  4.06    1       1  Sat     0     2
14   3.02    0       0  Sun     0     2
92   1.00    0       1  Fri     0     2
179  3.55    1       1  Sun     0     2
102  2.50    0       1  Sat     0     3

[183 rows x 6 columns]

In [222]:
import warnings
warnings.filterwarnings("ignore")

In [223]:
X_test["sex"]=le1.transform(X_test['sex'])
X_test["smoker"]=le2.transform(X_test["smoker"])
X_test["time"]=le3.transform(X_test["time"])

In [224]:
X_test.head()

      tip  sex  smoker   day  time  size
24   3.18    1       0   Sat     0     2
6    2.00    1       0   Sun     0     2
153  2.00    1       0   Sun     0     4
211  5.16    1       1   Sat     0     4
198  2.00    0       1  Thur     1     2

In [225]:
#onehot encoding---column transformer
from sklearn.compose import ColumnTransformer

In [226]:
from sklearn.preprocessing import OneHotEncoder

In [227]:
ct=ColumnTransformer(transformers=[('onehot',OneHotEncoder(drop='first'),[3])],remainder="passthrough")

In [228]:
import sys
import numpy
numpy.set_printoptions(threshold=sys.maxsize)
X_train=ct.fit_transform(X_train)

In [229]:
X_test=ct.transform(X_test)

In [230]:
X_test

array([[1.  , 0.  , 0.  , 3.18, 1.  , 0.  , 0.  , 2.  ],
       [0.  , 1.  , 0.  , 2.  , 1.  , 0.  , 0.  , 2.  ],
       [0.  , 1.  , 0.  , 2.  , 1.  , 0.  , 0.  , 4.  ],
       [1.  , 0.  , 0.  , 5.16, 1.  , 1.  , 0.  , 4.  ],
       [0.  , 0.  , 1.  , 2.  , 0.  , 1.  , 1.  , 2.  ],
       [0.  , 1.  , 0.  , 2.  , 1.  , 1.  , 0.  , 2.  ],
       [0.  , 0.  , 1.  , 2.56, 1.  , 1.  , 1.  , 2.  ],
       [0.  , 0.  , 1.  , 2.52, 0.  , 0.  , 1.  , 2.  ],
       [0.  , 1.  , 0.  , 3.23, 1.  , 0.  , 0.  , 2.  ],
       [0.  , 0.  , 0.  , 3.  , 0.  , 1.  , 0.  , 2.  ],
       [0.  , 1.  , 0.  , 3.  , 1.  , 0.  , 0.  , 2.  ],
       [1.  , 0.  , 0.  , 1.47, 1.  , 0.  , 0.  , 2.  ],
       [0.  , 0.  , 1.  , 1.5 , 0.  , 0.  , 1.  , 2.  ],
       [0.  , 1.  , 0.  , 2.  , 1.  , 1.  , 0.  , 2.  ],
       [0.  , 0.  , 1.  , 1.83, 0.  , 0.  , 1.  , 1.  ],
       [0.  , 0.  , 1.  , 1.36, 0.  , 0.  , 1.  , 3.  ],
       [0.  , 0.  , 1.  , 4.  , 1.  , 1.  , 1.  , 3.  ],
       [0.  , 1.  , 0.  , 3.92, 1.  , 0.  , 0.  , 2.  ],
       [1.  , 0.  , 0.  , 2.47, 0.  , 0.  , 0.  , 2.  ],
       [0.  , 0.  , 1.  , 5.  , 1.  , 0.  , 1.  , 5.  ],
       [1.  , 0.  , 0.  , 2.45, 0.  , 0.  , 0.  , 4.  ],
       [1.  , 0.  , 0.  , 3.35, 1.  , 0.  , 0.  , 3.  ],
       [1.  , 0.  , 0.  , 4.  , 0.  , 1.  , 0.  , 2.  ],
       [1.  , 0.  , 0.  , 1.45, 1.  , 0.  , 0.  , 2.  ],
       [0.  , 1.  , 0.  , 3.5 , 0.  , 1.  , 0.  , 3.  ],
       [0.  , 0.  , 1.  , 2.31, 1.  , 0.  , 1.  , 2.  ],
       [0.  , 1.  , 0.  , 1.71, 1.  , 0.  , 0.  , 2.  ],
       [1.  , 0.  , 0.  , 5.  , 0.  , 1.  , 0.  , 2.  ],
       [0.  , 1.  , 0.  , 2.  , 1.  , 0.  , 0.  , 4.  ],
       [0.  , 1.  , 0.  , 5.  , 1.  , 0.  , 0.  , 6.  ],
       [0.  , 1.  , 0.  , 4.  , 1.  , 0.  , 0.  , 3.  ],
       [1.  , 0.  , 0.  , 1.44, 1.  , 1.  , 0.  , 2.  ],
       [1.  , 0.  , 0.  , 2.34, 1.  , 0.  , 0.  , 4.  ],
       [1.  , 0.  , 0.  , 3.21, 1.  , 1.  , 0.  , 2.  ],
       [0.  , 1.  , 0.  , 3.5 , 0.  , 0.  , 0.  , 3.  ],
       [0.  , 0.  , 1.  , 2.92, 0.  , 0.  , 1.  , 4.  ],
       [0.  , 0.  , 0.  , 1.5 , 1.  , 1.  , 0.  , 2.  ],
       [0.  , 0.  , 1.  , 5.  , 0.  , 1.  , 1.  , 4.  ],
       [0.  , 0.  , 1.  , 2.75, 0.  , 0.  , 1.  , 2.  ],
       [1.  , 0.  , 0.  , 2.  , 1.  , 1.  , 0.  , 2.  ],
       [1.  , 0.  , 0.  , 1.25, 1.  , 0.  , 0.  , 2.  ],
       [0.  , 0.  , 1.  , 2.  , 0.  , 0.  , 1.  , 2.  ],
       [0.  , 1.  , 0.  , 2.55, 1.  , 0.  , 0.  , 2.  ],
       [0.  , 1.  , 0.  , 1.67, 0.  , 0.  , 0.  , 3.  ],
       [0.  , 0.  , 1.  , 2.  , 1.  , 1.  , 1.  , 2.  ],
       [1.  , 0.  , 0.  , 1.  , 0.  , 1.  , 0.  , 1.  ],
       [1.  , 0.  , 0.  , 1.61, 0.  , 1.  , 0.  , 2.  ],
       [1.  , 0.  , 0.  , 2.31, 1.  , 0.  , 0.  , 3.  ],
       [0.  , 0.  , 1.  , 1.44, 1.  , 0.  , 1.  , 2.  ],
       [1.  , 0.  , 0.  , 2.72, 1.  , 0.  , 0.  , 2.  ],
       [1.  , 0.  , 0.  , 2.03, 1.  , 1.  , 0.  , 2.  ],
       [0.  , 0.  , 0.  , 4.  , 1.  , 1.  , 0.  , 2.  ],
       [0.  , 1.  , 0.  , 4.5 , 1.  , 0.  , 0.  , 4.  ],
       [0.  , 0.  , 1.  , 2.03, 1.  , 0.  , 1.  , 2.  ],
       [0.  , 1.  , 0.  , 3.51, 1.  , 0.  , 0.  , 2.  ],
       [0.  , 0.  , 1.  , 2.  , 1.  , 0.  , 1.  , 2.  ],
       [0.  , 1.  , 0.  , 5.15, 1.  , 1.  , 0.  , 2.  ],
       [1.  , 0.  , 0.  , 1.75, 1.  , 0.  , 0.  , 2.  ],
       [0.  , 1.  , 0.  , 2.74, 1.  , 0.  , 0.  , 3.  ],
       [1.  , 0.  , 0.  , 3.  , 1.  , 1.  , 0.  , 3.  ],
       [0.  , 1.  , 0.  , 5.14, 0.  , 0.  , 0.  , 5.  ]])

In [231]:
#support vector regrssion
from sklearn.svm import SVR
svr=SVR()

In [232]:
svr.fit(X_train,y_train)

SVR()

In [233]:
y_pred=svr.predict(X_test)

In [234]:
from sklearn.metrics import r2_score ,mean_absolute_error

In [235]:
r2_score(y_test,y_pred)

0.49798620106004743

In [236]:
#tuning
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC

In [237]:
param_grid={'C': [0.1,.1,10,100,1000],
    'gamma':[1,0.1,0.01,0.001,0.0001],
    'kernel':['rbf']

}

In [238]:
grid=GridSearchCV(SVC(),param_grid=param_grid,cv=5,verbose=3,refit=True)

In [239]:
grid.fit(X_train,y_train)

Fitting 5 folds for each of 25 candidates, totalling 125 fits
[CV 1/5] END ..........C=0.1, gamma=1, kernel=rbf;, score=nan total time=   0.0s
[CV 2/5] END ..........C=0.1, gamma=1, kernel=rbf;, score=nan total time=   0.0s
[CV 3/5] END ..........C=0.1, gamma=1, kernel=rbf;, score=nan total time=   0.0s
[CV 4/5] END ..........C=0.1, gamma=1, kernel=rbf;, score=nan total time=   0.0s
[CV 5/5] END ..........C=0.1, gamma=1, kernel=rbf;, score=nan total time=   0.0s
[CV 1/5] END ........C=0.1, gamma=0.1, kernel=rbf;, score=nan total time=   0.0s
[CV 2/5] END ........C=0.1, gamma=0.1, kernel=rbf;, score=nan total time=   0.0s
[CV 3/5] END ........C=0.1, gamma=0.1, kernel=rbf;, score=nan total time=   0.0s
[CV 4/5] END ........C=0.1, gamma=0.1, kernel=rbf;, score=nan total time=   0.0s
[CV 5/5] END ........C=0.1, gamma=0.1, kernel=rbf;, score=nan total time=   0.0s
[CV 1/5] END .......C=0.1, gamma=0.01, kernel=rbf;, score=nan total time=   0.0s
[CV 2/5] END .......C=0.1, gamma=0.01, kernel=rbf;, score=nan total time=   0.0s
[CV 3/5] END .......C=0.1, gamma=0.01, kernel=rbf;, score=nan total time=   0.0s
[CV 4/5] END .......C=0.1, gamma=0.01, kernel=rbf;, score=nan total time=   0.0s
[CV 5/5] END .......C=0.1, gamma=0.01, kernel=rbf;, score=nan total time=   0.0s
[CV 1/5] END ......C=0.1, gamma=0.001, kernel=rbf;, score=nan total time=   0.0s
[CV 2/5] END ......C=0.1, gamma=0.001, kernel=rbf;, score=nan total time=   0.0s
[CV 3/5] END ......C=0.1, gamma=0.001, kernel=rbf;, score=nan total time=   0.0s
[CV 4/5] END ......C=0.1, gamma=0.001, kernel=rbf;, score=nan total time=   0.0s
[CV 5/5] END ......C=0.1, gamma=0.001, kernel=rbf;, score=nan total time=   0.0s
[CV 1/5] END .....C=0.1, gamma=0.0001, kernel=rbf;, score=nan total time=   0.0s
[CV 2/5] END .....C=0.1, gamma=0.0001, kernel=rbf;, score=nan total time=   0.0s
[CV 3/5] END .....C=0.1, gamma=0.0001, kernel=rbf;, score=nan total time=   0.0s
[CV 4/5] END .....C=0.1, gamma=0.0001, kernel=rbf;, score=nan total time=   0.0s
[CV 5/5] END .....C=0.1, gamma=0.0001, kernel=rbf;, score=nan total time=   0.0s
[CV 1/5] END ..........C=0.1, gamma=1, kernel=rbf;, score=nan total time=   0.0s
[CV 2/5] END ..........C=0.1, gamma=1, kernel=rbf;, score=nan total time=   0.0s
[CV 3/5] END ..........C=0.1, gamma=1, kernel=rbf;, score=nan total time=   0.0s
[CV 4/5] END ..........C=0.1, gamma=1, kernel=rbf;, score=nan total time=   0.0s
[CV 5/5] END ..........C=0.1, gamma=1, kernel=rbf;, score=nan total time=   0.0s
[CV 1/5] END ........C=0.1, gamma=0.1, kernel=rbf;, score=nan total time=   0.0s
[CV 2/5] END ........C=0.1, gamma=0.1, kernel=rbf;, score=nan total time=   0.0s
[CV 3/5] END ........C=0.1, gamma=0.1, kernel=rbf;, score=nan total time=   0.0s
[CV 4/5] END ........C=0.1, gamma=0.1, kernel=rbf;, score=nan total time=   0.0s
[CV 5/5] END ........C=0.1, gamma=0.1, kernel=rbf;, score=nan total time=   0.0s
[CV 1/5] END .......C=0.1, gamma=0.01, kernel=rbf;, score=nan total time=   0.0s
[CV 2/5] END .......C=0.1, gamma=0.01, kernel=rbf;, score=nan total time=   0.0s
[CV 3/5] END .......C=0.1, gamma=0.01, kernel=rbf;, score=nan total time=   0.0s
[CV 4/5] END .......C=0.1, gamma=0.01, kernel=rbf;, score=nan total time=   0.0s
[CV 5/5] END .......C=0.1, gamma=0.01, kernel=rbf;, score=nan total time=   0.0s
[CV 1/5] END ......C=0.1, gamma=0.001, kernel=rbf;, score=nan total time=   0.0s
[CV 2/5] END ......C=0.1, gamma=0.001, kernel=rbf;, score=nan total time=   0.0s
[CV 3/5] END ......C=0.1, gamma=0.001, kernel=rbf;, score=nan total time=   0.0s
[CV 4/5] END ......C=0.1, gamma=0.001, kernel=rbf;, score=nan total time=   0.0s
[CV 5/5] END ......C=0.1, gamma=0.001, kernel=rbf;, score=nan total time=   0.0s
[CV 1/5] END .....C=0.1, gamma=0.0001, kernel=rbf;, score=nan total time=   0.0s
[CV 2/5] END .....C=0.1, gamma=0.0001, kernel=rbf;, score=nan total time=   0.0s
[CV 3/5] END .....C=0.1, gamma=0.0001, kernel=rbf;, score=nan total time=   0.0s
[CV 4/5] END .....C=0.1, gamma=0.0001, kernel=rbf;, score=nan total time=   0.0s
[CV 5/5] END .....C=0.1, gamma=0.0001, kernel=rbf;, score=nan total time=   0.0s
[CV 1/5] END ...........C=10, gamma=1, kernel=rbf;, score=nan total time=   0.0s
[CV 2/5] END ...........C=10, gamma=1, kernel=rbf;, score=nan total time=   0.0s
[CV 3/5] END ...........C=10, gamma=1, kernel=rbf;, score=nan total time=   0.0s
[CV 4/5] END ...........C=10, gamma=1, kernel=rbf;, score=nan total time=   0.0s
[CV 5/5] END ...........C=10, gamma=1, kernel=rbf;, score=nan total time=   0.0s
[CV 1/5] END .........C=10, gamma=0.1, kernel=rbf;, score=nan total time=   0.0s
[CV 2/5] END .........C=10, gamma=0.1, kernel=rbf;, score=nan total time=   0.0s
[CV 3/5] END .........C=10, gamma=0.1, kernel=rbf;, score=nan total time=   0.0s
[CV 4/5] END .........C=10, gamma=0.1, kernel=rbf;, score=nan total time=   0.0s
[CV 5/5] END .........C=10, gamma=0.1, kernel=rbf;, score=nan total time=   0.0s
[CV 1/5] END ........C=10, gamma=0.01, kernel=rbf;, score=nan total time=   0.0s
[CV 2/5] END ........C=10, gamma=0.01, kernel=rbf;, score=nan total time=   0.0s
[CV 3/5] END ........C=10, gamma=0.01, kernel=rbf;, score=nan total time=   0.0s
[CV 4/5] END ........C=10, gamma=0.01, kernel=rbf;, score=nan total time=   0.0s
[CV 5/5] END ........C=10, gamma=0.01, kernel=rbf;, score=nan total time=   0.0s
[CV 1/5] END .......C=10, gamma=0.001, kernel=rbf;, score=nan total time=   0.0s
[CV 2/5] END .......C=10, gamma=0.001, kernel=rbf;, score=nan total time=   0.0s
[CV 3/5] END .......C=10, gamma=0.001, kernel=rbf;, score=nan total time=   0.0s

[CV 4/5] END .......C=10, gamma=0.001, kernel=rbf;, score=nan total time=   0.0s
[CV 5/5] END .......C=10, gamma=0.001, kernel=rbf;, score=nan total time=   0.0s
[CV 1/5] END ......C=10, gamma=0.0001, kernel=rbf;, score=nan total time=   0.0s
[CV 2/5] END ......C=10, gamma=0.0001, kernel=rbf;, score=nan total time=   0.0s
[CV 3/5] END ......C=10, gamma=0.0001, kernel=rbf;, score=nan total time=   0.0s
[CV 4/5] END ......C=10, gamma=0.0001, kernel=rbf;, score=nan total time=   0.0s
[CV 5/5] END ......C=10, gamma=0.0001, kernel=rbf;, score=nan total time=   0.0s
[CV 1/5] END ..........C=100, gamma=1, kernel=rbf;, score=nan total time=   0.0s
[CV 2/5] END ..........C=100, gamma=1, kernel=rbf;, score=nan total time=   0.0s
[CV 3/5] END ..........C=100, gamma=1, kernel=rbf;, score=nan total time=   0.0s
[CV 4/5] END ..........C=100, gamma=1, kernel=rbf;, score=nan total time=   0.0s
[CV 5/5] END ..........C=100, gamma=1, kernel=rbf;, score=nan total time=   0.0s
[CV 1/5] END ........C=100, gamma=0.1, kernel=rbf;, score=nan total time=   0.0s
[CV 2/5] END ........C=100, gamma=0.1, kernel=rbf;, score=nan total time=   0.0s
[CV 3/5] END ........C=100, gamma=0.1, kernel=rbf;, score=nan total time=   0.0s
[CV 4/5] END ........C=100, gamma=0.1, kernel=rbf;, score=nan total time=   0.0s
[CV 5/5] END ........C=100, gamma=0.1, kernel=rbf;, score=nan total time=   0.0s
[CV 1/5] END .......C=100, gamma=0.01, kernel=rbf;, score=nan total time=   0.0s
[CV 2/5] END .......C=100, gamma=0.01, kernel=rbf;, score=nan total time=   0.0s
[CV 3/5] END .......C=100, gamma=0.01, kernel=rbf;, score=nan total time=   0.0s
[CV 4/5] END .......C=100, gamma=0.01, kernel=rbf;, score=nan total time=   0.0s
[CV 5/5] END .......C=100, gamma=0.01, kernel=rbf;, score=nan total time=   0.0s
[CV 1/5] END ......C=100, gamma=0.001, kernel=rbf;, score=nan total time=   0.0s
[CV 2/5] END ......C=100, gamma=0.001, kernel=rbf;, score=nan total time=   0.0s
[CV 3/5] END ......C=100, gamma=0.001, kernel=rbf;, score=nan total time=   0.0s
[CV 4/5] END ......C=100, gamma=0.001, kernel=rbf;, score=nan total time=   0.0s
[CV 5/5] END ......C=100, gamma=0.001, kernel=rbf;, score=nan total time=   0.0s
[CV 1/5] END .....C=100, gamma=0.0001, kernel=rbf;, score=nan total time=   0.0s
[CV 2/5] END .....C=100, gamma=0.0001, kernel=rbf;, score=nan total time=   0.0s
[CV 3/5] END .....C=100, gamma=0.0001, kernel=rbf;, score=nan total time=   0.0s
[CV 4/5] END .....C=100, gamma=0.0001, kernel=rbf;, score=nan total time=   0.0s
[CV 5/5] END .....C=100, gamma=0.0001, kernel=rbf;, score=nan total time=   0.0s
[CV 1/5] END .........C=1000, gamma=1, kernel=rbf;, score=nan total time=   0.0s
[CV 2/5] END .........C=1000, gamma=1, kernel=rbf;, score=nan total time=   0.0s
[CV 3/5] END .........C=1000, gamma=1, kernel=rbf;, score=nan total time=   0.0s
[CV 4/5] END .........C=1000, gamma=1, kernel=rbf;, score=nan total time=   0.0s
[CV 5/5] END .........C=1000, gamma=1, kernel=rbf;, score=nan total time=   0.0s
[CV 1/5] END .......C=1000, gamma=0.1, kernel=rbf;, score=nan total time=   0.0s
[CV 2/5] END .......C=1000, gamma=0.1, kernel=rbf;, score=nan total time=   0.0s
[CV 3/5] END .......C=1000, gamma=0.1, kernel=rbf;, score=nan total time=   0.0s
[CV 4/5] END .......C=1000, gamma=0.1, kernel=rbf;, score=nan total time=   0.0s
[CV 5/5] END .......C=1000, gamma=0.1, kernel=rbf;, score=nan total time=   0.0s
[CV 1/5] END ......C=1000, gamma=0.01, kernel=rbf;, score=nan total time=   0.0s
[CV 2/5] END ......C=1000, gamma=0.01, kernel=rbf;, score=nan total time=   0.0s
[CV 3/5] END ......C=1000, gamma=0.01, kernel=rbf;, score=nan total time=   0.0s
[CV 4/5] END ......C=1000, gamma=0.01, kernel=rbf;, score=nan total time=   0.0s
[CV 5/5] END ......C=1000, gamma=0.01, kernel=rbf;, score=nan total time=   0.0s
[CV 1/5] END .....C=1000, gamma=0.001, kernel=rbf;, score=nan total time=   0.0s
[CV 2/5] END .....C=1000, gamma=0.001, kernel=rbf;, score=nan total time=   0.0s
[CV 3/5] END .....C=1000, gamma=0.001, kernel=rbf;, score=nan total time=   0.0s
[CV 4/5] END .....C=1000, gamma=0.001, kernel=rbf;, score=nan total time=   0.0s
[CV 5/5] END .....C=1000, gamma=0.001, kernel=rbf;, score=nan total time=   0.0s
[CV 1/5] END ....C=1000, gamma=0.0001, kernel=rbf;, score=nan total time=   0.0s
[CV 2/5] END ....C=1000, gamma=0.0001, kernel=rbf;, score=nan total time=   0.0s
[CV 3/5] END ....C=1000, gamma=0.0001, kernel=rbf;, score=nan total time=   0.0s
[CV 4/5] END ....C=1000, gamma=0.0001, kernel=rbf;, score=nan total time=   0.0s
[CV 5/5] END ....C=1000, gamma=0.0001, kernel=rbf;, score=nan total time=   0.0s

ValueError:
All the 125 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
125 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\ADMIN\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\model_selection\_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ADMIN\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\base.py", line 1363, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "c:\Users\ADMIN\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\svm\_base.py", line 207, in fit
    y = self._validate_targets(y)
  File "c:\Users\ADMIN\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\svm\_base.py", line 747, in _validate_targets
    check_classification_targets(y)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "c:\Users\ADMIN\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\multiclass.py", line 221, in check_classification_targets
    raise ValueError(
    ...<3 lines>...
    )
ValueError: Unknown label type: continuous. Maybe you are trying to fit a classifier, which expects discrete classes on a regression target with continuous values.

In [ ]:
grid.best_params_

AttributeError: 'GridSearchCV' object has no attribute 'best_params_'

In [ ]:
from sklearn.svm import SVR
from sklearn.model_selection import GridSearchCV

param_grid = {
    'C': [0.1, 1, 10, 100, 1000],
    'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
    'kernel': ['rbf']
}

grid = GridSearchCV(SVR(), param_grid=param_grid, cv=5, verbose=3, refit=True)
grid.fit(X_train, y_train)  # now y_train is continuous, so this works correctly

Fitting 5 folds for each of 25 candidates, totalling 125 fits
[CV 1/5] END .......C=0.1, gamma=1, kernel=rbf;, score=-0.114 total time=   0.0s
[CV 2/5] END .......C=0.1, gamma=1, kernel=rbf;, score=-0.008 total time=   0.0s
[CV 3/5] END .......C=0.1, gamma=1, kernel=rbf;, score=-0.003 total time=   0.0s
[CV 4/5] END .......C=0.1, gamma=1, kernel=rbf;, score=-0.015 total time=   0.0s
[CV 5/5] END .......C=0.1, gamma=1, kernel=rbf;, score=-0.123 total time=   0.0s
[CV 1/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.019 total time=   0.0s
[CV 2/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.096 total time=   0.0s
[CV 3/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.078 total time=   0.0s
[CV 4/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.099 total time=   0.0s
[CV 5/5] END .....C=0.1, gamma=0.1, kernel=rbf;, score=-0.020 total time=   0.0s
[CV 1/5] END ....C=0.1, gamma=0.01, kernel=rbf;, score=-0.102 total time=   0.0s
[CV 2/5] END .....C=0.1, gamma=0.01, kernel=rbf;, score=0.017 total time=   0.0s
[CV 3/5] END .....C=0.1, gamma=0.01, kernel=rbf;, score=0.008 total time=   0.0s
[CV 4/5] END .....C=0.1, gamma=0.01, kernel=rbf;, score=0.022 total time=   0.0s
[CV 5/5] END ....C=0.1, gamma=0.01, kernel=rbf;, score=-0.114 total time=   0.0s
[CV 1/5] END ...C=0.1, gamma=0.001, kernel=rbf;, score=-0.155 total time=   0.0s
[CV 2/5] END ...C=0.1, gamma=0.001, kernel=rbf;, score=-0.031 total time=   0.0s
[CV 3/5] END ...C=0.1, gamma=0.001, kernel=rbf;, score=-0.027 total time=   0.0s
[CV 4/5] END ...C=0.1, gamma=0.001, kernel=rbf;, score=-0.028 total time=   0.0s
[CV 5/5] END ...C=0.1, gamma=0.001, kernel=rbf;, score=-0.160 total time=   0.0s
[CV 1/5] END ..C=0.1, gamma=0.0001, kernel=rbf;, score=-0.161 total time=   0.0s
[CV 2/5] END ..C=0.1, gamma=0.0001, kernel=rbf;, score=-0.038 total time=   0.0s
[CV 3/5] END ..C=0.1, gamma=0.0001, kernel=rbf;, score=-0.032 total time=   0.0s
[CV 4/5] END ..C=0.1, gamma=0.0001, kernel=rbf;, score=-0.035 total time=   0.0s
[CV 5/5] END ..C=0.1, gamma=0.0001, kernel=rbf;, score=-0.165 total time=   0.0s
[CV 1/5] END ..........C=1, gamma=1, kernel=rbf;, score=0.126 total time=   0.0s
[CV 2/5] END ..........C=1, gamma=1, kernel=rbf;, score=0.229 total time=   0.0s
[CV 3/5] END ..........C=1, gamma=1, kernel=rbf;, score=0.214 total time=   0.0s
[CV 4/5] END ..........C=1, gamma=1, kernel=rbf;, score=0.153 total time=   0.0s
[CV 5/5] END ..........C=1, gamma=1, kernel=rbf;, score=0.122 total time=   0.0s
[CV 1/5] END ........C=1, gamma=0.1, kernel=rbf;, score=0.493 total time=   0.0s
[CV 2/5] END ........C=1, gamma=0.1, kernel=rbf;, score=0.467 total time=   0.0s
[CV 3/5] END ........C=1, gamma=0.1, kernel=rbf;, score=0.330 total time=   0.0s
[CV 4/5] END ........C=1, gamma=0.1, kernel=rbf;, score=0.425 total time=   0.0s
[CV 5/5] END ........C=1, gamma=0.1, kernel=rbf;, score=0.204 total time=   0.0s
[CV 1/5] END .......C=1, gamma=0.01, kernel=rbf;, score=0.197 total time=   0.0s
[CV 2/5] END .......C=1, gamma=0.01, kernel=rbf;, score=0.374 total time=   0.0s
[CV 3/5] END .......C=1, gamma=0.01, kernel=rbf;, score=0.264 total time=   0.0s
[CV 4/5] END .......C=1, gamma=0.01, kernel=rbf;, score=0.366 total time=   0.0s
[CV 5/5] END .......C=1, gamma=0.01, kernel=rbf;, score=0.088 total time=   0.0s
[CV 1/5] END .....C=1, gamma=0.001, kernel=rbf;, score=-0.094 total time=   0.0s
[CV 2/5] END ......C=1, gamma=0.001, kernel=rbf;, score=0.031 total time=   0.0s
[CV 3/5] END ......C=1, gamma=0.001, kernel=rbf;, score=0.015 total time=   0.0s
[CV 4/5] END ......C=1, gamma=0.001, kernel=rbf;, score=0.036 total time=   0.0s
[CV 5/5] END .....C=1, gamma=0.001, kernel=rbf;, score=-0.106 total time=   0.0s
[CV 1/5] END ....C=1, gamma=0.0001, kernel=rbf;, score=-0.155 total time=   0.0s
[CV 2/5] END ....C=1, gamma=0.0001, kernel=rbf;, score=-0.031 total time=   0.0s
[CV 3/5] END ....C=1, gamma=0.0001, kernel=rbf;, score=-0.027 total time=   0.0s
[CV 4/5] END ....C=1, gamma=0.0001, kernel=rbf;, score=-0.028 total time=   0.0s
[CV 5/5] END ....C=1, gamma=0.0001, kernel=rbf;, score=-0.160 total time=   0.0s
[CV 1/5] END .........C=10, gamma=1, kernel=rbf;, score=0.327 total time=   0.0s
[CV 2/5] END .........C=10, gamma=1, kernel=rbf;, score=0.539 total time=   0.0s
[CV 3/5] END .........C=10, gamma=1, kernel=rbf;, score=0.529 total time=   0.0s
[CV 4/5] END .........C=10, gamma=1, kernel=rbf;, score=0.249 total time=   0.0s
[CV 5/5] END .........C=10, gamma=1, kernel=rbf;, score=0.336 total time=   0.0s
[CV 1/5] END .......C=10, gamma=0.1, kernel=rbf;, score=0.599 total time=   0.0s
[CV 2/5] END .......C=10, gamma=0.1, kernel=rbf;, score=0.633 total time=   0.0s
[CV 3/5] END .......C=10, gamma=0.1, kernel=rbf;, score=0.431 total time=   0.0s
[CV 4/5] END .......C=10, gamma=0.1, kernel=rbf;, score=0.595 total time=   0.0s
[CV 5/5] END .......C=10, gamma=0.1, kernel=rbf;, score=0.246 total time=   0.0s
[CV 1/5] END ......C=10, gamma=0.01, kernel=rbf;, score=0.530 total time=   0.0s
[CV 2/5] END ......C=10, gamma=0.01, kernel=rbf;, score=0.629 total time=   0.0s
[CV 3/5] END ......C=10, gamma=0.01, kernel=rbf;, score=0.383 total time=   0.0s
[CV 4/5] END ......C=10, gamma=0.01, kernel=rbf;, score=0.629 total time=   0.0s
[CV 5/5] END ......C=10, gamma=0.01, kernel=rbf;, score=0.216 total time=   0.0s
[CV 1/5] END .....C=10, gamma=0.001, kernel=rbf;, score=0.230 total time=   0.0s
[CV 2/5] END .....C=10, gamma=0.001, kernel=rbf;, score=0.461 total time=   0.0s
[CV 3/5] END .....C=10, gamma=0.001, kernel=rbf;, score=0.304 total time=   0.0s
[CV 4/5] END .....C=10, gamma=0.001, kernel=rbf;, score=0.440 total time=   0.0s
[CV 5/5] END .....C=10, gamma=0.001, kernel=rbf;, score=0.105 total time=   0.0s
[CV 1/5] END ...C=10, gamma=0.0001, kernel=rbf;, score=-0.093 total time=   0.0s
[CV 2/5] END ....C=10, gamma=0.0001, kernel=rbf;, score=0.032 total time=   0.0s
[CV 3/5] END ....C=10, gamma=0.0001, kernel=rbf;, score=0.016 total time=   0.0s
[CV 4/5] END ....C=10, gamma=0.0001, kernel=rbf;, score=0.038 total time=   0.0s
[CV 5/5] END ...C=10, gamma=0.0001, kernel=rbf;, score=-0.106 total time=   0.0s
[CV 1/5] END ........C=100, gamma=1, kernel=rbf;, score=0.303 total time=   0.0s
[CV 2/5] END ........C=100, gamma=1, kernel=rbf;, score=0.538 total time=   0.0s
[CV 3/5] END ........C=100, gamma=1, kernel=rbf;, score=0.610 total time=   0.0s
[CV 4/5] END ........C=100, gamma=1, kernel=rbf;, score=0.102 total time=   0.0s
[CV 5/5] END .......C=100, gamma=1, kernel=rbf;, score=-0.009 total time=   0.0s
[CV 1/5] END ......C=100, gamma=0.1, kernel=rbf;, score=0.344 total time=   0.0s
[CV 2/5] END ......C=100, gamma=0.1, kernel=rbf;, score=0.687 total time=   0.0s
[CV 3/5] END ......C=100, gamma=0.1, kernel=rbf;, score=0.414 total time=   0.0s
[CV 4/5] END ......C=100, gamma=0.1, kernel=rbf;, score=0.442 total time=   0.0s
[CV 5/5] END ......C=100, gamma=0.1, kernel=rbf;, score=0.286 total time=   0.0s
[CV 1/5] END .....C=100, gamma=0.01, kernel=rbf;, score=0.607 total time=   0.0s
[CV 2/5] END .....C=100, gamma=0.01, kernel=rbf;, score=0.687 total time=   0.0s
[CV 3/5] END .....C=100, gamma=0.01, kernel=rbf;, score=0.388 total time=   0.0s
[CV 4/5] END .....C=100, gamma=0.01, kernel=rbf;, score=0.683 total time=   0.0s
[CV 5/5] END .....C=100, gamma=0.01, kernel=rbf;, score=0.238 total time=   0.0s
[CV 1/5] END ....C=100, gamma=0.001, kernel=rbf;, score=0.536 total time=   0.0s
[CV 2/5] END ....C=100, gamma=0.001, kernel=rbf;, score=0.657 total time=   0.0s
[CV 3/5] END ....C=100, gamma=0.001, kernel=rbf;, score=0.376 total time=   0.0s
[CV 4/5] END ....C=100, gamma=0.001, kernel=rbf;, score=0.655 total time=   0.0s
[CV 5/5] END ....C=100, gamma=0.001, kernel=rbf;, score=0.215 total time=   0.0s
[CV 1/5] END ...C=100, gamma=0.0001, kernel=rbf;, score=0.234 total time=   0.0s
[CV 2/5] END ...C=100, gamma=0.0001, kernel=rbf;, score=0.468 total time=   0.0s
[CV 3/5] END ...C=100, gamma=0.0001, kernel=rbf;, score=0.308 total time=   0.0s
[CV 4/5] END ...C=100, gamma=0.0001, kernel=rbf;, score=0.445 total time=   0.0s
[CV 5/5] END ...C=100, gamma=0.0001, kernel=rbf;, score=0.109 total time=   0.0s
[CV 1/5] END ......C=1000, gamma=1, kernel=rbf;, score=-0.189 total time=   0.0s
[CV 2/5] END .......C=1000, gamma=1, kernel=rbf;, score=0.551 total time=   0.0s
[CV 3/5] END .......C=1000, gamma=1, kernel=rbf;, score=0.575 total time=   0.0s
[CV 4/5] END ......C=1000, gamma=1, kernel=rbf;, score=-0.624 total time=   0.0s
[CV 5/5] END ......C=1000, gamma=1, kernel=rbf;, score=-0.680 total time=   0.0s
[CV 1/5] END ....C=1000, gamma=0.1, kernel=rbf;, score=-0.115 total time=   0.0s
[CV 2/5] END .....C=1000, gamma=0.1, kernel=rbf;, score=0.640 total time=   0.0s
[CV 3/5] END .....C=1000, gamma=0.1, kernel=rbf;, score=0.446 total time=   0.0s
[CV 4/5] END .....C=1000, gamma=0.1, kernel=rbf;, score=0.196 total time=   0.0s
[CV 5/5] END .....C=1000, gamma=0.1, kernel=rbf;, score=0.288 total time=   0.0s
[CV 1/5] END ....C=1000, gamma=0.01, kernel=rbf;, score=0.644 total time=   0.0s
[CV 2/5] END ....C=1000, gamma=0.01, kernel=rbf;, score=0.709 total time=   0.0s
[CV 3/5] END ....C=1000, gamma=0.01, kernel=rbf;, score=0.431 total time=   0.0s
[CV 4/5] END ....C=1000, gamma=0.01, kernel=rbf;, score=0.640 total time=   0.0s
[CV 5/5] END ....C=1000, gamma=0.01, kernel=rbf;, score=0.178 total time=   0.0s
[CV 1/5] END ...C=1000, gamma=0.001, kernel=rbf;, score=0.621 total time=   0.0s
[CV 2/5] END ...C=1000, gamma=0.001, kernel=rbf;, score=0.674 total time=   0.0s
[CV 3/5] END ...C=1000, gamma=0.001, kernel=rbf;, score=0.360 total time=   0.0s
[CV 4/5] END ...C=1000, gamma=0.001, kernel=rbf;, score=0.677 total time=   0.0s
[CV 5/5] END ...C=1000, gamma=0.001, kernel=rbf;, score=0.230 total time=   0.0s
[CV 1/5] END ..C=1000, gamma=0.0001, kernel=rbf;, score=0.536 total time=   0.0s
[CV 2/5] END ..C=1000, gamma=0.0001, kernel=rbf;, score=0.659 total time=   0.0s
[CV 3/5] END ..C=1000, gamma=0.0001, kernel=rbf;, score=0.375 total time=   0.0s
[CV 4/5] END ..C=1000, gamma=0.0001, kernel=rbf;, score=0.658 total time=   0.0s
[CV 5/5] END ..C=1000, gamma=0.0001, kernel=rbf;, score=0.212 total time=   0.0s

GridSearchCV(cv=5, estimator=SVR(),
             param_grid={'C': [0.1, 1, 10, 100, 1000],
                         'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
                         'kernel': ['rbf']},
             verbose=3)

In [ ]:
grid.best_params_

{'C': 100, 'gamma': 0.01, 'kernel': 'rbf'}

In [ ]:
grid_pred=grid.predict(X_test)

In [ ]:
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

print("R² score:", r2_score(y_test, grid_pred))
print("Mean Absolute Error:", mean_absolute_error(y_test, grid_pred))
print("Mean Squared Error:", mean_squared_error(y_test, grid_pred))

R² score: 0.5630727637616448
Mean Absolute Error: 4.26048397387227
Mean Squared Error: 34.21448856486327