In [170]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [171]:
data=sns.load_dataset("tips")

In [172]:
data.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [173]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB

In [174]:
data.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [175]:
X=data[['total_bill', 'tip', 'sex', 'smoker', 'day', 'size']]

In [176]:
y=data["time"]

In [177]:
from sklearn.model_selection import train_test_split

In [178]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=0)

In [179]:
from sklearn.preprocessing import LabelEncoder

In [180]:
le1=LabelEncoder()
le2=LabelEncoder()
le3=LabelEncoder()

In [181]:
X_train

     total_bill   tip     sex smoker   day  size
171       15.81  3.16    Male    Yes   Sat     2
89        21.16  3.00    Male     No  Thur     2
157       25.00  3.75  Female     No   Sun     4
219       30.14  3.09  Female    Yes   Sat     4
234       15.53  3.00    Male    Yes   Sat     2
..          ...   ...     ...    ...   ...   ...
67         3.07  1.00  Female    Yes   Sat     1
192       28.44  2.56    Male    Yes  Thur     2
117       10.65  1.50  Female     No  Thur     2
47        32.40  6.00    Male     No   Sun     4
172        7.25  5.15    Male    Yes   Sun     2

[183 rows x 6 columns]

In [182]:
y_train

171    Dinner
89      Lunch
157    Dinner
219    Dinner
234    Dinner
        ...
67     Dinner
192     Lunch
117     Lunch
47     Dinner
172    Dinner
Name: time, Length: 183, dtype: category
Categories (2, object): ['Lunch', 'Dinner']

In [183]:
y_train.unique()

['Dinner', 'Lunch']
Categories (2, object): ['Lunch', 'Dinner']

In [184]:
y_train=le1.fit_transform(y_train)

In [185]:
y_train

array([0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 1, 1, 0, 0])

In [186]:
y_test=le1.transform(y_test)

In [187]:
y_test

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0])

In [188]:
X_train["smoker"]=le1.fit_transform(X_train["smoker"])

In [189]:
X_train["sex"]=le2.fit_transform(X_train["sex"])

In [190]:
X_test["sex"]=le2.transform(X_test["sex"])

In [191]:
X_test

     total_bill   tip  sex smoker   day  size
64        17.59  2.64    1     No   Sat     3
63        18.29  3.76    1    Yes   Sat     4
55        19.49  3.51    1     No   Sun     2
111        7.25  1.00    0     No   Sat     1
225       16.27  2.50    0    Yes   Fri     2
..          ...   ...  ...    ...   ...   ...
116       29.93  5.07    1     No   Sun     4
33        20.69  2.45    0     No   Sat     4
122       14.26  2.50    1     No  Thur     2
161       12.66  2.50    1     No   Sun     2
96        27.28  4.00    1    Yes   Fri     2

[61 rows x 6 columns]

In [192]:
X_train

     total_bill   tip  sex  smoker   day  size
171       15.81  3.16    1       1   Sat     2
89        21.16  3.00    1       0  Thur     2
157       25.00  3.75    0       0   Sun     4
219       30.14  3.09    0       1   Sat     4
234       15.53  3.00    1       1   Sat     2
..          ...   ...  ...     ...   ...   ...
67         3.07  1.00    0       1   Sat     1
192       28.44  2.56    1       1  Thur     2
117       10.65  1.50    0       0  Thur     2
47        32.40  6.00    1       0   Sun     4
172        7.25  5.15    1       1   Sun     2

[183 rows x 6 columns]

In [193]:
X_test["smoker"]=le1.transform(X_test["smoker"])

In [194]:
X_test

     total_bill   tip  sex  smoker   day  size
64        17.59  2.64    1       0   Sat     3
63        18.29  3.76    1       1   Sat     4
55        19.49  3.51    1       0   Sun     2
111        7.25  1.00    0       0   Sat     1
225       16.27  2.50    0       1   Fri     2
..          ...   ...  ...     ...   ...   ...
116       29.93  5.07    1       0   Sun     4
33        20.69  2.45    0       0   Sat     4
122       14.26  2.50    1       0  Thur     2
161       12.66  2.50    1       0   Sun     2
96        27.28  4.00    1       1   Fri     2

[61 rows x 6 columns]

In [195]:
y_test

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0])

In [196]:
X_train

     total_bill   tip  sex  smoker   day  size
171       15.81  3.16    1       1   Sat     2
89        21.16  3.00    1       0  Thur     2
157       25.00  3.75    0       0   Sun     4
219       30.14  3.09    0       1   Sat     4
234       15.53  3.00    1       1   Sat     2
..          ...   ...  ...     ...   ...   ...
67         3.07  1.00    0       1   Sat     1
192       28.44  2.56    1       1  Thur     2
117       10.65  1.50    0       0  Thur     2
47        32.40  6.00    1       0   Sun     4
172        7.25  5.15    1       1   Sun     2

[183 rows x 6 columns]

In [197]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [198]:
ct=ColumnTransformer(transformers=[('oneHot',OneHotEncoder(drop='first'),[4])],remainder='passthrough')

In [199]:
import sys
import numpy
numpy.set_printoptions(threshold=sys.maxsize)
X_train=ct.fit_transform(X_train)

In [200]:
X_test=ct.transform(X_test)

In [201]:
X_train

array([[ 1.  ,  0.  ,  0.  , 15.81,  3.16,  1.  ,  1.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  , 21.16,  3.  ,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 25.  ,  3.75,  0.  ,  0.  ,  4.  ],
       [ 1.  ,  0.  ,  0.  , 30.14,  3.09,  0.  ,  1.  ,  4.  ],
       [ 1.  ,  0.  ,  0.  , 15.53,  3.  ,  1.  ,  1.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  , 16.47,  3.23,  0.  ,  1.  ,  3.  ],
       [ 1.  ,  0.  ,  0.  , 32.83,  1.17,  1.  ,  1.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 10.33,  1.67,  0.  ,  0.  ,  3.  ],
       [ 0.  ,  0.  ,  0.  , 28.97,  3.  ,  1.  ,  1.  ,  2.  ],
       [ 0.  ,  0.  ,  0.  , 15.38,  3.  ,  0.  ,  1.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 10.51,  1.25,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 24.59,  3.61,  0.  ,  0.  ,  4.  ],
       [ 1.  ,  0.  ,  0.  , 14.31,  4.  ,  0.  ,  1.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 13.81,  2.  ,  1.  ,  1.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  , 18.64,  1.36,  0.  ,  0.  ,  3.  ],
       [ 0.  ,  1.  ,  0.  , 34.81,  5.2 ,  0.  ,  0.  ,  4.  ],
       [ 1.  ,  0.  ,  0.  , 16.45,  2.47,  0.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 13.37,  2.  ,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  , 18.26,  3.25,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  ,  8.51,  1.25,  0.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 11.59,  1.5 ,  1.  ,  1.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 16.04,  2.24,  1.  ,  0.  ,  3.  ],
       [ 0.  ,  1.  ,  0.  , 18.43,  3.  ,  1.  ,  0.  ,  4.  ],
       [ 0.  ,  1.  ,  0.  , 23.68,  3.31,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 17.26,  2.74,  1.  ,  0.  ,  3.  ],
       [ 1.  ,  0.  ,  0.  , 19.82,  3.18,  1.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  ,  9.55,  1.45,  1.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  ,  7.74,  1.44,  1.  ,  1.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 20.29,  3.21,  1.  ,  1.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 38.01,  3.  ,  1.  ,  1.  ,  4.  ],
       [ 0.  ,  1.  ,  0.  , 34.63,  3.55,  1.  ,  1.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 28.17,  6.5 ,  0.  ,  1.  ,  3.  ],
       [ 1.  ,  0.  ,  0.  , 20.65,  3.35,  1.  ,  0.  ,  3.  ],
       [ 0.  ,  1.  ,  0.  , 45.35,  3.5 ,  1.  ,  1.  ,  3.  ],
       [ 0.  ,  0.  ,  1.  , 22.82,  2.18,  1.  ,  0.  ,  3.  ],
       [ 0.  ,  1.  ,  0.  , 25.56,  4.34,  1.  ,  0.  ,  4.  ],
       [ 1.  ,  0.  ,  0.  , 35.83,  4.67,  0.  ,  0.  ,  3.  ],
       [ 0.  ,  0.  ,  1.  , 19.44,  3.  ,  1.  ,  1.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 10.29,  2.6 ,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  , 15.95,  2.  ,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  , 12.74,  2.01,  0.  ,  1.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  , 19.08,  1.5 ,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  , 13.03,  2.  ,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 10.27,  1.71,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  , 14.15,  2.  ,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 31.85,  3.18,  1.  ,  1.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  ,  8.52,  1.48,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 17.46,  2.54,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 14.83,  3.02,  0.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 12.69,  2.  ,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 12.54,  2.5 ,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  0.  ,  0.  , 13.42,  3.48,  0.  ,  1.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 17.92,  4.08,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 16.21,  2.  ,  0.  ,  0.  ,  3.  ],
       [ 0.  ,  1.  ,  0.  , 22.23,  5.  ,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 20.76,  2.24,  1.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 29.03,  5.92,  1.  ,  0.  ,  3.  ],
       [ 0.  ,  1.  ,  0.  , 21.5 ,  3.5 ,  1.  ,  0.  ,  4.  ],
       [ 1.  ,  0.  ,  0.  , 50.81, 10.  ,  1.  ,  1.  ,  3.  ],
       [ 1.  ,  0.  ,  0.  , 11.02,  1.98,  1.  ,  1.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 15.69,  1.5 ,  1.  ,  1.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 16.49,  2.  ,  1.  ,  0.  ,  4.  ],
       [ 0.  ,  1.  ,  0.  , 21.01,  3.5 ,  1.  ,  0.  ,  3.  ],
       [ 1.  ,  0.  ,  0.  , 48.27,  6.73,  1.  ,  0.  ,  4.  ],
       [ 0.  ,  0.  ,  1.  ,  7.51,  2.  ,  1.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 20.45,  3.  ,  1.  ,  0.  ,  4.  ],
       [ 0.  ,  1.  ,  0.  ,  9.68,  1.32,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  , 19.81,  4.19,  0.  ,  1.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  , 13.16,  2.75,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 19.77,  2.  ,  1.  ,  0.  ,  4.  ],
       [ 0.  ,  1.  ,  0.  , 38.07,  4.  ,  1.  ,  0.  ,  3.  ],
       [ 1.  ,  0.  ,  0.  , 26.59,  3.41,  1.  ,  1.  ,  3.  ],
       [ 0.  ,  0.  ,  0.  , 21.01,  3.  ,  1.  ,  1.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 24.55,  2.  ,  1.  ,  0.  ,  4.  ],
       [ 0.  ,  0.  ,  0.  , 16.32,  4.3 ,  0.  ,  1.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  , 16.43,  2.3 ,  0.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 10.77,  1.47,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 23.95,  2.55,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 16.99,  1.01,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  0.  ,  0.  , 22.75,  3.25,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  0.  ,  0.  , 40.17,  4.73,  1.  ,  1.  ,  4.  ],
       [ 1.  ,  0.  ,  0.  , 15.01,  2.09,  1.  ,  1.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 18.04,  3.  ,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 28.55,  2.05,  1.  ,  0.  ,  3.  ],
       [ 0.  ,  0.  ,  1.  , 34.83,  5.17,  0.  ,  0.  ,  4.  ],
       [ 1.  ,  0.  ,  0.  , 22.67,  2.  ,  1.  ,  1.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  , 34.3 ,  6.7 ,  1.  ,  0.  ,  6.  ],
       [ 1.  ,  0.  ,  0.  , 39.42,  7.58,  1.  ,  0.  ,  4.  ],
       [ 1.  ,  0.  ,  0.  , 12.9 ,  1.1 ,  0.  ,  1.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  , 27.05,  5.  ,  0.  ,  0.  ,  6.  ],
       [ 0.  ,  0.  ,  1.  , 22.76,  3.  ,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  0.  ,  0.  , 11.35,  2.5 ,  0.  ,  1.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  , 20.27,  2.83,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  , 10.34,  2.  ,  1.  ,  1.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 17.82,  1.75,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  ,  8.77,  2.  ,  1.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 20.23,  2.01,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  , 15.98,  2.03,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  , 13.42,  1.68,  0.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 13.28,  2.72,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 40.55,  3.  ,  1.  ,  1.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 38.73,  3.  ,  1.  ,  1.  ,  4.  ],
       [ 0.  ,  0.  ,  1.  , 13.  ,  2.  ,  0.  ,  1.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 20.9 ,  3.5 ,  0.  ,  1.  ,  3.  ],
       [ 0.  ,  0.  ,  0.  , 22.49,  3.5 ,  1.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 13.27,  2.5 ,  0.  ,  1.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 35.26,  5.  ,  0.  ,  0.  ,  4.  ],
       [ 0.  ,  0.  ,  1.  , 24.08,  2.92,  0.  ,  0.  ,  4.  ],
       [ 1.  ,  0.  ,  0.  , 44.3 ,  2.5 ,  0.  ,  1.  ,  3.  ],
       [ 1.  ,  0.  ,  0.  , 24.06,  3.6 ,  1.  ,  0.  ,  3.  ],
       [ 1.  ,  0.  ,  0.  , 26.41,  1.5 ,  0.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 10.63,  2.  ,  0.  ,  1.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 20.08,  3.15,  1.  ,  0.  ,  3.  ],
       [ 0.  ,  1.  ,  0.  , 10.34,  1.66,  1.  ,  0.  ,  3.  ],
       [ 0.  ,  0.  ,  1.  , 11.69,  2.31,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  , 16.58,  4.  ,  1.  ,  1.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 13.94,  3.06,  1.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 15.36,  1.64,  1.  ,  1.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  , 11.17,  1.5 ,  0.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 10.07,  1.25,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 16.29,  3.71,  1.  ,  0.  ,  3.  ],
       [ 1.  ,  0.  ,  0.  , 18.69,  2.31,  1.  ,  0.  ,  3.  ],
       [ 0.  ,  0.  ,  1.  , 12.26,  2.  ,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  ,  9.94,  1.56,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 17.51,  3.  ,  0.  ,  1.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 30.46,  2.  ,  1.  ,  1.  ,  5.  ],
       [ 0.  ,  0.  ,  1.  , 11.38,  2.  ,  0.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 17.78,  3.27,  1.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 21.7 ,  4.3 ,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 23.17,  6.5 ,  1.  ,  1.  ,  4.  ],
       [ 0.  ,  1.  ,  0.  , 25.71,  4.  ,  0.  ,  0.  ,  3.  ],
       [ 0.  ,  1.  ,  0.  , 13.81,  2.  ,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 13.13,  2.  ,  1.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 18.35,  2.5 ,  1.  ,  0.  ,  4.  ],
       [ 0.  ,  0.  ,  1.  , 18.71,  4.  ,  1.  ,  1.  ,  3.  ],
       [ 0.  ,  0.  ,  1.  , 14.52,  2.  ,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 20.69,  5.  ,  1.  ,  0.  ,  5.  ],
       [ 1.  ,  0.  ,  0.  , 24.01,  2.  ,  1.  ,  1.  ,  4.  ],
       [ 0.  ,  0.  ,  0.  , 10.09,  2.  ,  0.  ,  1.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 15.06,  3.  ,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 31.71,  4.5 ,  1.  ,  0.  ,  4.  ],
       [ 0.  ,  0.  ,  1.  , 41.19,  5.  ,  1.  ,  0.  ,  5.  ],
       [ 0.  ,  0.  ,  1.  , 20.53,  4.  ,  1.  ,  1.  ,  4.  ],
       [ 0.  ,  0.  ,  1.  , 11.87,  1.63,  0.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 19.65,  3.  ,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 14.48,  2.  ,  1.  ,  1.  ,  2.  ],
       [ 0.  ,  0.  ,  0.  , 12.46,  1.5 ,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  , 10.07,  1.83,  0.  ,  0.  ,  1.  ],
       [ 1.  ,  0.  ,  0.  , 27.18,  2.  ,  0.  ,  1.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 32.9 ,  3.11,  1.  ,  1.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  , 17.29,  2.71,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  , 43.11,  5.  ,  0.  ,  1.  ,  4.  ],
       [ 1.  ,  0.  ,  0.  , 24.27,  2.03,  1.  ,  1.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 17.31,  3.5 ,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  ,  9.78,  1.73,  1.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 12.6 ,  1.  ,  1.  ,  1.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 26.86,  3.14,  0.  ,  1.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  , 27.2 ,  4.  ,  1.  ,  0.  ,  4.  ],
       [ 1.  ,  0.  ,  0.  , 17.81,  2.34,  1.  ,  0.  ,  4.  ],
       [ 0.  ,  1.  ,  0.  , 24.52,  3.48,  1.  ,  0.  ,  3.  ],
       [ 0.  ,  0.  ,  1.  , 16.66,  3.4 ,  1.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 22.12,  2.88,  0.  ,  1.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 16.82,  4.  ,  1.  ,  1.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 11.61,  3.39,  1.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 31.27,  5.  ,  1.  ,  0.  ,  3.  ],
       [ 0.  ,  0.  ,  1.  , 15.48,  2.02,  1.  ,  1.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 11.24,  1.76,  1.  ,  1.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  , 17.47,  3.5 ,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  , 24.71,  5.85,  1.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 28.15,  3.  ,  1.  ,  1.  ,  5.  ],
       [ 1.  ,  0.  ,  0.  , 12.02,  1.97,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  , 18.28,  4.  ,  1.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 16.31,  2.  ,  1.  ,  0.  ,  3.  ],
       [ 1.  ,  0.  ,  0.  , 20.29,  2.75,  0.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 25.89,  5.16,  1.  ,  1.  ,  4.  ],
       [ 0.  ,  1.  ,  0.  , 14.78,  3.23,  1.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 22.42,  3.48,  0.  ,  1.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  ,  7.56,  1.44,  1.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  ,  3.07,  1.  ,  0.  ,  1.  ,  1.  ],
       [ 0.  ,  0.  ,  1.  , 28.44,  2.56,  1.  ,  1.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  , 10.65,  1.5 ,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 32.4 ,  6.  ,  1.  ,  0.  ,  4.  ],
       [ 0.  ,  1.  ,  0.  ,  7.25,  5.15,  1.  ,  1.  ,  2.  ]])

In [202]:
X_test

array([[ 1.  ,  0.  ,  0.  , 17.59,  2.64,  1.  ,  0.  ,  3.  ],
       [ 1.  ,  0.  ,  0.  , 18.29,  3.76,  1.  ,  1.  ,  4.  ],
       [ 0.  ,  1.  ,  0.  , 19.49,  3.51,  1.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  ,  7.25,  1.  ,  0.  ,  0.  ,  1.  ],
       [ 0.  ,  0.  ,  0.  , 16.27,  2.5 ,  0.  ,  1.  ,  2.  ],
       [ 0.  ,  0.  ,  0.  ,  5.75,  1.  ,  0.  ,  1.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 17.92,  3.08,  1.  ,  1.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 23.33,  5.65,  1.  ,  1.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 18.15,  3.5 ,  0.  ,  1.  ,  3.  ],
       [ 0.  ,  1.  ,  0.  , 34.65,  3.68,  1.  ,  1.  ,  4.  ],
       [ 1.  ,  0.  ,  0.  , 25.28,  5.  ,  0.  ,  1.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 25.21,  4.29,  1.  ,  1.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 14.07,  2.5 ,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  , 13.  ,  2.  ,  0.  ,  1.  ,  2.  ],
       [ 0.  ,  0.  ,  0.  , 13.42,  1.58,  1.  ,  1.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 30.4 ,  5.6 ,  1.  ,  0.  ,  4.  ],
       [ 0.  ,  0.  ,  1.  ,  8.35,  1.5 ,  0.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 14.  ,  3.  ,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  , 18.78,  3.  ,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 23.1 ,  4.  ,  1.  ,  1.  ,  3.  ],
       [ 1.  ,  0.  ,  0.  , 30.06,  2.  ,  1.  ,  1.  ,  3.  ],
       [ 1.  ,  0.  ,  0.  , 20.92,  4.08,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  , 16.  ,  2.  ,  1.  ,  1.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 15.04,  1.96,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  , 13.51,  2.  ,  1.  ,  1.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  , 16.4 ,  2.5 ,  0.  ,  1.  ,  2.  ],
       [ 0.  ,  0.  ,  0.  , 12.16,  2.2 ,  1.  ,  1.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  , 29.8 ,  4.2 ,  0.  ,  0.  ,  6.  ],
       [ 0.  ,  1.  ,  0.  , 25.29,  4.71,  1.  ,  0.  ,  4.  ],
       [ 1.  ,  0.  ,  0.  , 15.77,  2.23,  0.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 14.73,  2.2 ,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  , 12.48,  2.52,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 15.42,  1.57,  1.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 10.59,  1.61,  0.  ,  1.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 18.29,  3.  ,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 13.39,  2.61,  0.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 16.93,  3.07,  0.  ,  0.  ,  3.  ],
       [ 0.  ,  0.  ,  1.  , 10.33,  2.  ,  0.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 48.33,  9.  ,  1.  ,  0.  ,  4.  ],
       [ 0.  ,  0.  ,  0.  , 15.98,  3.  ,  0.  ,  0.  ,  3.  ],
       [ 0.  ,  0.  ,  0.  ,  8.58,  1.92,  1.  ,  1.  ,  1.  ],
       [ 0.  ,  0.  ,  1.  , 12.43,  1.8 ,  0.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 15.69,  3.  ,  1.  ,  1.  ,  3.  ],
       [ 0.  ,  1.  ,  0.  , 29.85,  5.14,  0.  ,  0.  ,  5.  ],
       [ 1.  ,  0.  ,  0.  , 12.76,  2.23,  0.  ,  1.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 16.97,  3.5 ,  0.  ,  0.  ,  3.  ],
       [ 1.  ,  0.  ,  0.  , 18.24,  3.76,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 21.58,  3.92,  1.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 17.07,  3.  ,  0.  ,  0.  ,  3.  ],
       [ 0.  ,  1.  ,  0.  , 26.88,  3.12,  1.  ,  0.  ,  4.  ],
       [ 0.  ,  0.  ,  1.  , 32.68,  5.  ,  1.  ,  1.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 17.89,  2.  ,  1.  ,  1.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 20.49,  4.06,  1.  ,  1.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 48.17,  5.  ,  1.  ,  0.  ,  6.  ],
       [ 0.  ,  1.  ,  0.  ,  9.6 ,  4.  ,  0.  ,  1.  ,  2.  ],
       [ 0.  ,  0.  ,  0.  , 12.03,  1.5 ,  1.  ,  1.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 29.93,  5.07,  1.  ,  0.  ,  4.  ],
       [ 1.  ,  0.  ,  0.  , 20.69,  2.45,  0.  ,  0.  ,  4.  ],
       [ 0.  ,  0.  ,  1.  , 14.26,  2.5 ,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 12.66,  2.5 ,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  0.  ,  0.  , 27.28,  4.  ,  1.  ,  1.  ,  2.  ]])

In [203]:
from sklearn.naive_bayes import GaussianNB

In [204]:
gnb=GaussianNB()

In [205]:
gnb.fit(X_train,y_train)

GaussianNB()

In [206]:
y_pred=gnb.predict(X_test)

In [207]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [210]:
print(accuracy_score(y_test,y_pred))

0.9016393442622951

In [211]:
print(confusion_matrix(y_test,y_pred))

[[44  1]
 [ 5 11]]

In [214]:

# New input from user
new_data = pd.DataFrame([{
    "total_bill": 25.5,
    "tip": 3.5,
    "sex": "Male",
    "smoker": "Yes",
    "day": "Sun",
    "size": 2
}])

# Apply same encodings
new_data["smoker"] = le1.transform(new_data["smoker"])
new_data["sex"] = le2.transform(new_data["sex"])

# Apply same column transformer
new_data_enc = ct.transform(new_data)

# Predict
pred = gnb.predict(new_data_enc)
print("Predicted Time:", le1.inverse_transform(pred)[0])

ValueError: X has 6 features, but ColumnTransformer is expecting 8 features as input.

In [216]:
# New input
new_data = pd.DataFrame([{
    "total_bill": 25.5,
    "tip": 3.5,
    "sex": "Male",
    "smoker": "Yes",
    "day": "Sun",
    "size": 2
}])

# Apply same encoders as training
new_data["smoker"] = le1.transform(new_data["smoker"])   # same as training
new_data["sex"]    = le2.transform(new_data["sex"])      # same as training
# ⚠️ DO NOT encode "day" manually, because ct will handle it

# Now transform using ct
new_data_enc = ct.transform(new_data)

# Predict
pred = gnb.predict(new_data_enc)
print("Predicted Time:", le1.inverse_transform(pred)[0])

ValueError: X has 6 features, but ColumnTransformer is expecting 8 features as input.

In [ ]:
# %% Import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# %% Load dataset
data = sns.load_dataset("tips")

# %% Features and target
X = data[['total_bill', 'time', 'sex', 'smoker', 'day', 'size']]
y = data["'tip'"]

# %% Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=0)

# %% Label encoding for y, sex, smoker
le_y = LabelEncoder()
le_smoker = LabelEncoder()
le_sex = LabelEncoder()

y_train = le_y.fit_transform(y_train)
y_test = le_y.transform(y_test)

X_train["smoker"] = le_smoker.fit_transform(X_train["smoker"])
X_test["smoker"] = le_smoker.transform(X_test["smoker"])

X_train["sex"] = le_sex.fit_transform(X_train["sex"])
X_test["sex"] = le_sex.transform(X_test["sex"])



X_train = ct.fit_transform(X_train)
X_test = ct.transform(X_test)

# %% Train Naive Bayes model
gnb = GaussianNB()
gnb.fit(X_train, y_train)

# %% Predictions and evaluation
y_pred = gnb.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))

# %% ---- Predict on new user input ----
new_data = pd.DataFrame([{
    "total_bill": 25.5,
    
    "sex": "Male",
    "smoker": "Yes",
    "day": "Sun",
    "size": 2
}])

# Apply same encoders
new_data["smoker"] = le_smoker.transform(new_data["smoker"])
new_data["sex"] = le_sex.transform(new_data["sex"])
# "day" left raw because ct handles it

# Transform with column transformer
new_data_enc = ct.transform(new_data)

# Predict
pred = gnb.predict(new_data_enc)
print("Predicted Time:", le_y.inverse_transform(pred))

ValueError: y contains previously unseen labels: [np.float64(1.57), np.float64(1.58), np.float64(1.61), np.float64(1.8), np.float64(1.92), np.float64(1.96), np.float64(2.2), np.float64(2.23), np.float64(2.45), np.float64(2.52), np.float64(2.61), np.float64(2.64), np.float64(3.07), np.float64(3.08), np.float64(3.12), np.float64(3.51), np.float64(3.68), np.float64(3.76), np.float64(3.92), np.float64(4.06), np.float64(4.2), np.float64(4.29), np.float64(4.71), np.float64(5.07), np.float64(5.14), np.float64(5.6), np.float64(5.65), np.float64(9.0)]

In [224]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# %% Load dataset
data = sns.load_dataset("tips")
data.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [226]:
X = data[['total_bill', 'sex', 'smoker', 'day', 'time','size']]
y = data['tip']